### ISSUE TITLE
LICSBAS_flt2geotiff.py

### ISSUE THREAD

**Issue by Komal6814** [yumorishita/LiCSBAS#127]
Dear Sir,
I am trying the LICSBAS_flt2geotiff.py step, but  I don't know where to get the path of the dem parameters file (EQA.dem_par).  Have I downloaded this parameter file from anywhere? Please guide me!!!

**Comment by Komal6814** [comment]
Dear Sir,
This problem is resolved and now I am stuck in the LICSBAS_decomposeLOS.py step.  Further, Please help me to know about the East and North component  LOS data file. I used these files from the folder GEOCml1, but the error is  "no LOS data from east".

**Comment by yumorishita** [comment]
First please search and see past issues, e.g., https://github.com/yumorishita/LiCSBAS/issues/39, https://github.com/yumorishita/LiCSBAS/issues/110, https://github.com/yumorishita/LiCSBAS/issues/116.

What frames did you use? You need at least one ascending and one descending frames to decompose.

**Comment by yyzzccmg** [comment]
Dear Yu Morishita,
Thank you for the LiCSBAS software. I have processed a frame succesfully but it gave me an error while displaying the time series and velocity by cum. Here is the error
LiCSBAS_plot_ts.py -i TS_GACOSml4/cum_filt.h5 

LiCSBAS_plot_ts.py ver1.13.3 20210205 Y. Morishita
LiCSBAS_plot_ts.py -i TS_GACOSml4/cum_filt.h5

Reading TS_GACOSml4/cum_filt.h5
Traceback (most recent call last):
  File "/home/yazici/Licsbas/LiCSBAS-master/LiCSBAS/bin/LiCSBAS_plot_ts.py", line 361, in <module>
    refx1, refx2, refy1, refy2 = [int(s) for s in re.split('[:/]', refarea)]
  File "/home/yazici/miniconda3/envs/licsbas/lib/python3.9/re.py", line 231, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: cannot use a string pattern on a bytes-like object

I couldnt solve the error. I would be happy if you give me a suggestion.
Best regards

**Comment by yyzzccmg** [comment]
How should i update it correctly? I have tried to change the gedit LiCSBAS_plot_ts.py but didnt work. 
Thanks in advance

**Comment by miladmz** [comment]
> 
Hi 
how you fix it?
