### ISSUE TITLE
Error line 311...Value ifgs area regarded as bad!

### ISSUE THREAD

**Issue by cglanchares** [yumorishita/LiCSBAS#129]
I don´t know what this error means, could somebody help me, please :-)

---

Traceback (most recent call last):
  File "/home/topografia/detektia/LiCSBAS-master/bin/LiCSBAS11_check_unw.py", line 356, in <module>
    sys.exit(main())
  File "/home/topografia/detektia/LiCSBAS-master/bin/LiCSBAS11_check_unw.py", line 311, in main
    raise ValueError('All ifgs are regarded as bad!\nChange the parameters or check the input ifgs.\n')
ValueError: All ifgs are regarded as bad!
Change the parameters or check the input ifgs.

------

**Comment by yumorishita** [comment]
It means all the unwrapped data are removed in the step1-1 with your thresholds. Check the unwrapped data and try changing the thresholds.
