### ISSUE TITLE
Step16

### ISSUE THREAD

**Issue by Alenhasha** [yumorishita/LiCSBAS#185]
Hi
I want to run step 16, but I have an error
What should I do?

 LiCSBAS16_filt_ts.py -t TS_GEOCml1GACOS -r 2 --n_para 1

LiCSBAS16_filt_ts.py ver1.5.1 20210311 Y. Morishita
LiCSBAS16_filt_ts.py -t TS_GEOCml1GACOS -r 2 --n_para 1
No bperp field found in cum.h5. Skip.

Size of image (w,l)      : 7255, 7410
Number of images         : 147
Width of filter in space : 2 km (44.6x36.1 pixel)
Width of filter in time  : 0.103 yr (37 days)
Deramp flag              : 2
hgt-linear flag          : False

Deramp ifgs with the degree of 2,
    0/147th image...
   10/147th image...
   20/147th image...
   30/147th image...
   40/147th image...
   50/147th image...
   60/147th image...
   70/147th image...
   80/147th image...
   90/147th image...
  100/147th image...
  110/147th image...
  120/147th image...
  130/147th image...
  140/147th image...

Create png for increment with 1 parallel processing...

HP filter in time, LP filter in space,
    0/147th image...
   10/147th image...
   20/147th image...
   30/147th image...
   40/147th image...
   50/147th image...
   60/147th image...
   70/147th image...
   80/147th image...
   90/147th image...
  100/147th image...
  110/147th image...
  120/147th image...
  130/147th image...
  140/147th image...

Create png for increment with 1 parallel processing...

Find stable reference point...
Selected ref: 1216:1217/4325:4326

Calculate velocity of filtered time series...
  First, solving 23251152/23337109th points with full cum...

MKL ERROR: Parameter 12 was incorrect on entry to DGELSD.
Traceback (most recent call last):
  File "/home/geodesy/LiCSBAS/bin/LiCSBAS16_filt_ts.py", line 791, in <module>
    sys.exit(main())
  File "/home/geodesy/LiCSBAS/bin/LiCSBAS16_filt_ts.py", line 543, in main
    vconst_tmp[bool_nonan_pt], vel_tmp[bool_nonan_pt] = np.linalg.lstsq(G, cum_pt[:, bool_nonan_pt], rcond=None)[0]
  File "<__array_function__ internals>", line 5, in lstsq
  File "/home/geodesy/miniconda3/envs/licsbas/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 2306, in lstsq
    x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
  File "/home/geodesy/miniconda3/envs/licsbas/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 100, in _raise_linalgerror_lstsq
    raise LinAlgError("SVD did not converge in Linear Least Squares")
numpy.linalg.LinAlgError: SVD did not converge in Linear Least Squares

**Comment by yumorishita** [comment]
I have never seen that error. The root cause seems to be in your environment.
I googled it and found a page: https://github.com/etal/cnvkit/issues/508#issuecomment-640369931
I suggest disabling MKL.

**Comment by Alenhasha** [comment]
Thank you very much for your suggestion
but when I installed "nomkl numpy scipy" I faced with this error.

Traceback (most recent call last):
  File "/home/geodesy/LiCSBAS/bin/LiCSBAS16_filt_ts.py", line 121, in <module>
    import LiCSBAS_io_lib as io_lib
  File "/home/geodesy/LiCSBAS/LiCSBAS_lib/LiCSBAS_io_lib.py", line 30, in <module>
    import statsmodels.api as sm
  File "/home/geodesy/miniconda3/envs/licsbas/lib/python3.9/site-packages/statsmodels/api.py", line 124, in <module>
    from .tsa import api as tsa
  File "/home/geodesy/miniconda3/envs/licsbas/lib/python3.9/site-packages/statsmodels/tsa/api.py", line 74, in <module>
    from .filters import api as filters, bk_filter, cf_filter, hp_filter
  File "/home/geodesy/miniconda3/envs/licsbas/lib/python3.9/site-packages/statsmodels/tsa/filters/api.py", line 6, in <module>
    from .filtertools import miso_lfilter, convolution_filter, recursive_filter
  File "/home/geodesy/miniconda3/envs/licsbas/lib/python3.9/site-packages/statsmodels/tsa/filters/filtertools.py", line 18, in <module>
    from scipy.signal.signaltools import _centered as trim_centered
ImportError: cannot import name '_centered' from 'scipy.signal.signaltools' (/home/geodesy/miniconda3/envs/licsbas/lib/python3.9/site-packages/scipy/signal/signaltools.py)

**Comment by yumorishita** [comment]
I have no idea. I suggest trying python3.8 because I have not used LiCSBAS in python3.9.
