### ISSUE TITLE
Data raw from the time series

### ISSUE THREAD

**Issue by alejobeap** [yumorishita/LiCSBAS#20]
Dear 

How can I get the time series data because I can only save it as an image ?

Thank you very much.

Pedro

**Comment by yumorishita** [comment]
You can use [LiCSBAS_cum2tstxt.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_cum2tstxtpy).

**Comment by alejobeap** [comment]
Dear
Thanks for your help. I'm Trying to use the code to transform to Geotiff, but I'm not sure that the -i (input file) is correct. 
LiCSBAS_flt2geotiff.py  -i TS_GEOCml1clip/cum_filt.h5 -p TS_GEOCml1clip/info/EQA.dem_par

LiCSBAS_flt2geotiff.py ver1.4 20200214 Y. Morishita
LiCSBAS_flt2geotiff.py -i TS_GEOCml1clip/cum_filt.h5 -p TS_GEOCml1clip/info/EQA.dem_par
Use gdal module
Traceback (most recent call last):
  File "/home/pespin/LICSBAS/LiCSBAS/bin/LiCSBAS_flt2geotiff.py", line 219, in <module>
    sys.exit(main())
  File "/home/pespin/LICSBAS/LiCSBAS/bin/LiCSBAS_flt2geotiff.py", line 186, in main
    data = io_lib.read_img(infile, length, width, endian=endian)
  File "/home/pespin/LICSBAS/LiCSBAS/LiCSBAS_lib/LiCSBAS_io_lib.py", line 146, in read_img
    data = np.fromfile(file, dtype=dtype).reshape((length, width))
ValueError: cannot reshape array of size 713073 into shape (72,112)

**Comment by yumorishita** [comment]
The input file for ​LiCSBAS_flt2geotiff.py must be in float format (not hdf5) as is written in the usage, which can be created by LiCSBAS_cum2vel.py or LiCSBAS_cum2flt.py. 

See also:
https://github.com/yumorishita/LiCSBAS/issues/11

**Comment by alejobeap** [comment]
Thanks for your help

**Comment by alejobeap** [comment]
Dear 
Again Thanks for your help.
At the time of processing choose a reference area for processing, is there any way to change this reference area?

Thank you
Greetings

**Comment by yumorishita** [comment]
You can set the reference area using the -r option in [LiCSBAS_cum2vel.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_cum2velpy) and [LiCSBAS_cum2flt.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_cum2fltpy).

**Comment by alejobeap** [comment]
Thanks
