### ISSUE TITLE
Error after run LiCSBAS03

### ISSUE THREAD

**Issue by InSAR2023** [yumorishita/LiCSBAS#216]
LiCSBAS03op_GACOS.py ver1.5.5 20201119 Y. Morishita
LiCSBAS03op_GACOS.py -i GEOCml -o GEOCml-GACOS -g GACOS --fillhole

Convert ztd/sltd.geo.tif files to sltd.geo files...
   90/ 90 sltd already exist. Skip

Correct unw data...
  419/434 corrected unw already exist. Skip
  4 parallel processing...
  Finished    0/  15th unw...
  Finished   10/  15th unw...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ahmed/mconda/miniconda3/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/ahmed/mconda/miniconda3/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/ahmed/LiCSBAS/bin/LiCSBAS03op_GACOS.py", line 511, in correct_wrapper
    ssltd = io_lib.read_img(ssltdfile, length_unw, width_unw)
  File "/home/ahmed/LiCSBAS/LiCSBAS_lib/LiCSBAS_io_lib.py", line 199, in read_img
    data = np.fromfile(file, dtype=dtype).reshape((length, width))
ValueError: cannot reshape array of size 9009152 into shape (2691,3348)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ahmed/LiCSBAS/bin/LiCSBAS03op_GACOS.py", line 550, in <module>
    sys.exit(main())
  File "/home/ahmed/LiCSBAS/bin/LiCSBAS03op_GACOS.py", line 353, in main
    _return = p.map(correct_wrapper, range(n_ifg2))
  File "/home/ahmed/mconda/miniconda3/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/ahmed/mconda/miniconda3/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
ValueError: cannot reshape array of size 9009152 into shape (2691,3348)

-----------------------
Python version: 3.10.9
  OK

Check required modues and versions
  astropy(5.2.1) OK
  bs4(4.11.2) OK
  h5py(3.8.0) OK
  matplotlib(3.2.2) OK
  numpy(1.23.1) OK
  psutil(5.9.4) OK
  requests(2.28.2) OK
  statsmodels(0.13.5) OK
  gdal(3.6.2) OK

Check LiCSBAS commands
  OK

Check LiCSBAS library
  OK

LiCSBAS install is OK

**Comment by InSAR2023** [comment]
> I recommend using [batch_LiCSBAS.sh](https://github.com/yumorishita/LiCSBAS/wiki/2_4_batch_proc).

Dear Dr. Morishita

Thank you for replying. 
This error occur in step 03 only.

Best regards,

**Comment by yumorishita** [comment]
Using [batch_LiCSBAS.sh](https://github.com/yumorishita/LiCSBAS/wiki/2_4_batch_proc) might solve the error.
