### ISSUE TITLE
Error after run step 11: quality check

### ISSUE THREAD

**Issue by Freedomance** [yumorishita/LiCSBAS#219]
Hi, when I run step11 quality check using such command:
 `LiCSBAS11_check_unw.py -d GEOCml1clip`, I encounted  this problem:
```
LiCSBAS11_check_unw.py ver1.3.3 20210402 Y. Morishita
LiCSBAS11_check_unw.py -d GEOCml1clip

coh_thre     : 0.05
unw_cov_thre : 0.3

Size         : 191 x 121

Reading unw and cc data...
    0/217th unw to identify valid area...
  100/217th unw to identify valid area...
  200/217th unw to identify valid area...
    0/217th cc and unw...
  100/217th cc and unw...
  200/217th cc and unw...
Traceback (most recent call last):
  File "/home/ljw/tools/LiCSBAS-1.5.11/bin/LiCSBAS11_check_unw.py", line 356, in <module>

0/217 ifgs are discarded from further processing.
ifg dates        unw_cov coh_av
    sys.exit(main())
  File "/home/ljw/tools/LiCSBAS-1.5.11/bin/LiCSBAS11_check_unw.py", line 331, in main
    plot_lib.plot_network(ifgdates, bperp, [], pngfile)
  File "/home/ljw/tools/LiCSBAS-1.5.11/LiCSBAS_lib/LiCSBAS_plot_lib.py", line 285, in plot_network
    ax.grid(b=True, which='major')
  File "/home/ljw/anaconda3/envs/LiCSBAS/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3196, in grid
    self.xaxis.grid(visible, which=which, **kwargs)
  File "/home/ljw/anaconda3/envs/LiCSBAS/lib/python3.10/site-packages/matplotlib/axis.py", line 1655, in grid
    self.set_tick_params(which='major', **gridkw)
  File "/home/ljw/anaconda3/envs/LiCSBAS/lib/python3.10/site-packages/matplotlib/axis.py", line 927, in set_tick_params
    kwtrans = self._translate_tick_params(kwargs)
  File "/home/ljw/anaconda3/envs/LiCSBAS/lib/python3.10/site-packages/matplotlib/axis.py", line 1071, in _translate_tick_params
    raise ValueError(
ValueError: keyword grid_b is not recognized; valid keywords are ['size', 'width', 'color', 'tickdir', 'pad', 'labelsize', 'labelcolor', 'zorder', 'gridOn', 'tick1On', 'tick2On', 'label1On', 'label2On', 'length', 'direction', 'left', 'bottom', 'right', 'top', 'labelleft', 'labelbottom', 'labelright', 'labeltop', 'labelrotation', 'grid_agg_filter', 'grid_alpha', 'grid_animated', 'grid_antialiased', 'grid_clip_box', 'grid_clip_on', 'grid_clip_path', 'grid_color', 'grid_dash_capstyle', 'grid_dash_joinstyle', 'grid_dashes', 'grid_data', 'grid_drawstyle', 'grid_figure', 'grid_fillstyle', 'grid_gapcolor', 'grid_gid', 'grid_in_layout', 'grid_label', 'grid_linestyle', 'grid_linewidth', 'grid_marker', 'grid_markeredgecolor', 'grid_markeredgewidth', 'grid_markerfacecolor', 'grid_markerfacecoloralt', 'grid_markersize', 'grid_markevery', 'grid_mouseover', 'grid_path_effects', 'grid_picker', 'grid_pickradius', 'grid_rasterized', 'grid_sketch_params', 'grid_snap', 'grid_solid_capstyle', 'grid_solid_joinstyle', 'grid_transform', 'grid_url', 'grid_visible', 'grid_xdata', 'grid_ydata', 'grid_zorder', 'grid_aa', 'grid_c', 'grid_ds', 'grid_ls', 'grid_lw', 'grid_mec', 'grid_mew', 'grid_mfc', 'grid_mfcalt', 'grid_ms']
```

**Comment by Freedomance** [comment]
I have solved the problem by modifying  the code in `LiCSBAS_plot_lib.py`. This maybe  due to the version of matplotlib. Because I  have encountered a new problem when run step 12: `ValueError: A colormap named "SCM.romaO" is already registered.`, and find resolution in issues. It's also because of the version of matplotlib.

**Comment by irmayolii** [comment]
My matplotlib version is 3.7.0
![image](https://user-images.githubusercontent.com/80675405/223164455-ad9bcfc8-0ce0-4ec0-bdd7-f77bd207b162.png)

**Comment by irmayolii** [comment]
I have solved the problem by downgrade matplotlib version to 3.1 and it run successfully

**Comment by mdavid3** [comment]
I'm using Ubuntu 18.04 and getting the same error. Can you help me how to downgrade the matplotlib version?

**Comment by ArgoBagus10** [comment]
you can use code 
pip show matplotlib
conda install matplotlib==3.1.0

![image](https://user-images.githubusercontent.com/114724695/235337177-bac997d7-bb2a-4f6a-97d6-80215890b029.png)
