### ISSUE TITLE
Update LiCSBAS

### ISSUE THREAD

**Issue by khakim** [yumorishita/LiCSBAS#223]
Dear Yumorishita,

I would like to update the installed LiCSBAS. Please let me know a command line in ubuntu to do it.

Thanks.

**Comment by khakim** [comment]
I already installed the latest version of LiCSBAS.
However, I  still can't download GACOS data using LiCSBAS. The error messages are below

Download GACOS data
  There are 212 epochs from 20141121 to 20230102
  Searching available epochs (4 parallel)...
    0/212
   30/212
   20/212
   50/212
   10/212
   40/212
   70/212
  100/212
   60/212
   90/212
   80/212
  110/212
  140/212
  130/212
  120/212
  160/212
  150/212
  170/212
  210/212
  190/212
  200/212
  180/212
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/khakim/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/khakim/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/khakim/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/khakim/anaconda3/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/home/khakim/anaconda3/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/home/khakim/anaconda3/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/khakim/anaconda3/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/khakim/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/khakim/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/khakim/anaconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/khakim/anaconda3/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/khakim/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/khakim/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/khakim/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/khakim/anaconda3/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/home/khakim/anaconda3/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/home/khakim/anaconda3/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/khakim/anaconda3/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/khakim/anaconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/khakim/anaconda3/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/local/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 490, in check_gacos_wrapper
    response = requests.head(url_data, allow_redirects=True)
  File "/home/khakim/anaconda3/lib/python3.9/site-packages/requests/api.py", line 102, in head
    return request('head', url, **kwargs)
  File "/home/khakim/anaconda3/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/khakim/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/khakim/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/khakim/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 499, in <module>
    sys.exit(main())
  File "/usr/local/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 277, in main
    rc = p.map(check_gacos_wrapper, args)
  File "/home/khakim/anaconda3/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/khakim/anaconda3/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'(base) k(base) khak(ba(bas((((b(ba(ba((ba(base)(

**Comment by yumorishita** [comment]
Maybe there was a network connection issue. Please try again.
