### ISSUE TITLE
Error in running LiCSBAS02_ml_prep.py

### ISSUE THREAD

**Issue by mdehgani** [yumorishita/LiCSBAS#231]
I got the following error while running step 02: LiCSBAS02_ml_prep.py

LiCSBAS02_ml_prep.py -i GEOC -n 1

LiCSBAS02_ml_prep.py ver1.7.4 20201119 Y. Morishita
LiCSBAS02_ml_prep.py -i GEOC -n 1
Traceback (most recent call last):
  File "/home/dehghani/LiCSBAS/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 453, in <module>
    sys.exit(main())
  File "/home/dehghani/LiCSBAS/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 185, in main
    center_time = subp.check_output(['grep', 'center_time', metadata_file]).decode().split('=')[1].strip()
  File "/home/dehghani/anaconda3/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/dehghani/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['grep', 'center_time', '/home/dehghani/Fars_subsidence/test/137D_05960_131313/GEOC/metadata.txt']' returned non-zero exit status 1.

**Comment by mdehgani** [comment]
What is the problem?
