### ISSUE TITLE
error in step 11

### ISSUE THREAD

**Issue by liuanm** [yumorishita/LiCSBAS#238]
Hello,
I am getting an error in the 11 step

LiCSBAS11_check_unw.py ver1.3.3 20210402 Y. Morishita
LiCSBAS11_check_unw.py -d GEOCml1clip -u 0.2 -c 0.05

coh_thre     : 0.05
unw_cov_thre : 0.2

Size         : 701 x 731

Reading unw and cc data...
    0/ 98th unw to identify valid area...
    0/ 98th cc and unw...

0/98 ifgs are discarded from further processing.
ifg dates        unw_cov coh_av
Traceback (most recent call last):
  File "/usr/local/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 356, in <module>
    sys.exit(main())
  File "/usr/local/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 331, in main
    plot_lib.plot_network(ifgdates, bperp, [], pngfile)
  File "/usr/local/LiCSBAS/LiCSBAS_lib/LiCSBAS_plot_lib.py", line 285, in plot_network
    ax.grid(b=True, which='major')
  File "/usr/local/miniconda3/envs/licsbas/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3194, in grid
    self.xaxis.grid(visible, which=which, **kwargs)
  File "/usr/local/miniconda3/envs/licsbas/lib/python3.10/site-packages/matplotlib/axis.py", line 1660, in grid
    self.set_tick_params(which='major', **gridkw)
  File "/usr/local/miniconda3/envs/licsbas/lib/python3.10/site-packages/matplotlib/axis.py", line 932, in set_tick_params
    kwtrans = self._translate_tick_params(kwargs)
  File "/usr/local/miniconda3/envs/licsbas/lib/python3.10/site-packages/matplotlib/axis.py", line 1076, in _translate_tick_params
    raise ValueError(
ValueError: keyword grid_b is not recognized; valid keywords are ['size', 'width', 'color', 'tickdir', 'pad', 'labelsize', 'labelcolor', 'zorder', 'gridOn', 'tick1On', 'tick2On', 'label1On', 'label2On', 'length', 'direction', 'left', 'bottom', 'right', 'top', 'labelleft', 'labelbottom', 'labelright', 'labeltop', 'labelrotation', 'grid_agg_filter', 'grid_alpha', 'grid_animated', 'grid_antialiased', 'grid_clip_box', 'grid_clip_on', 'grid_clip_path', 'grid_color', 'grid_dash_capstyle', 'grid_dash_joinstyle', 'grid_dashes', 'grid_data', 'grid_drawstyle', 'grid_figure', 'grid_fillstyle', 'grid_gapcolor', 'grid_gid', 'grid_in_layout', 'grid_label', 'grid_linestyle', 'grid_linewidth', 'grid_marker', 'grid_markeredgecolor', 'grid_markeredgewidth', 'grid_markerfacecolor', 'grid_markerfacecoloralt', 'grid_markersize', 'grid_markevery', 'grid_mouseover', 'grid_path_effects', 'grid_picker', 'grid_pickradius', 'grid_rasterized', 'grid_sketch_params', 'grid_snap', 'grid_solid_capstyle', 'grid_solid_joinstyle', 'grid_transform', 'grid_url', 'grid_visible', 'grid_xdata', 'grid_ydata', 'grid_zorder', 'grid_aa', 'grid_c', 'grid_ds', 'grid_ls', 'grid_lw', 'grid_mec', 'grid_mew', 'grid_mfc', 'grid_mfcalt', 'grid_ms']

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/219
https://github.com/yumorishita/LiCSBAS/issues/224
https://github.com/yumorishita/LiCSBAS/issues/228
