### ISSUE TITLE
Error in batch_LiCSBAS.sh

### ISSUE THREAD

**Issue by dalalprohelika** [yumorishita/LiCSBAS#243]
![Screenshot from 2023-04-06 15-41-41](https://user-images.githubusercontent.com/96712513/230348271-6ffd3712-8419-4aa3-99b5-0fbd4bc29ab2.png)

I am having this error repeatedly while running the batch_LiCSBAS.sh

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1498886957

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1500877478

**Comment by MIEMESSI** [comment]
Hello Professor, how can I solve this problem，thanks

LiCSBAS05op_clip_unw.py -i GEOCml1 -o GEOCml1clip -g 92.54/92.57/34.48/34.52
Traceback (most recent call last):
  File "/home/pl/wx/LiCSBAS/bin/LiCSBAS05op_clip_unw.py", line 345, in <module>
    sys.exit(main())
  File "/home/pl/wx/LiCSBAS/bin/LiCSBAS05op_clip_unw.py", line 161, in main
    width = int(io_lib.get_param_par(mlipar, 'range_samples'))
  File "/home/pl/wx/LiCSBAS/LiCSBAS_lib/LiCSBAS_io_lib.py", line 236, in get_param_par
    value = subp.check_output(['grep', field,mlipar]).decode().split()[1].strip()
  File "/home/pl/anaconda3/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/pl/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['grep', 'range_samples', '/home/pl/wx/LiCSBAS/bin/143A_05651_131313/GEOCml1/slc.mli.par']' returned non-zero exit status 1.
