### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by yumorishita** [yumorishita/LiCSBAS#244]
Unfortunately, I cannot update this LiCSBAS repository for a reason.
All known issues are solved in [LiCSBAS2](https://github.com/yumorishita/LiCSBAS2) and it will keep updated. I recommend using LiCSBAS2 if you encounter an issue.

**Comment by yumorishita** [comment]
`ValueError: A colormap named "SCM.roma0" is already registered`
https://github.com/yumorishita/LiCSBAS/issues/176#issuecomment-1303308876
https://github.com/yumorishita/LiCSBAS/issues/195#issuecomment-1363954623
https://github.com/yumorishita/LiCSBAS/issues/198
Downgrade matplotlib, e.g., to 3.4.2.

**Comment by yumorishita** [comment]
Step16 (`LiCSBAS16_filt_ts.py`) gets stuck.
https://github.com/yumorishita/LiCSBAS/issues/62
https://github.com/yumorishita/LiCSBAS/issues/86
Try `p16_n_para="1"`.
https://github.com/yumorishita/LiCSBAS/blob/dfdb8fadf323c821f386ed60eb0e871288961a72/batch_LiCSBAS.sh#L111

Other parallel processing in other steps may also be stuck. In that case, try setting `p*_n_para="1"`  for the stuck step or setting for for all steps:

https://github.com/yumorishita/LiCSBAS/blob/5ca6550c8adbcb90e47aefc338d36ef33e122f03/batch_LiCSBAS.sh#L24

It seems that WSL tends to have such a stuck issue. I suggest using VirtualBox.

**Comment by terramare55** [comment]
Problem solved. It worked!
Thank you again

**Comment by yumorishita** [comment]
`ModuleNotFoundError: No module named '_gdal'`

https://github.com/yumorishita/LiCSBAS/issues/299

**Comment by yumorishita** [comment]
If you have any requests about LiCSAR products (not LiCSBAS), please send an email to 'Contact us' shown at the bottom of https://comet.nerc.ac.uk/COMET-LiCS-portal/.
https://github.com/yumorishita/LiCSBAS/issues/323#issuecomment-1914236392

**Comment by yumorishita** [comment]
Merge frames: https://github.com/yumorishita/LiCSBAS/issues/24

**Comment by yumorishita** [comment]
In step13:
```
File "LiCSBAS/bin/LiCSBAS13_sb_inv.py", line 785, in main
refy1s, refx1s = refy1s[0], refx1s[0] ## Only first index
IndexError: index 0 is out of bounds for axis 0 with size 0
```
In step12:
```
File "LiCSBAS/bin/LiCSBAS12_loop_closure.py", line 356, in main
refy1 = refyx[0][0] # start from 0, not 1
IndexError: index 0 is out of bounds for axis 0 with size 0
```

https://github.com/yumorishita/LiCSBAS/issues/6
https://github.com/yumorishita/LiCSBAS/issues/56
https://github.com/yumorishita/LiCSBAS/issues/63
https://github.com/yumorishita/LiCSBAS/issues/284
https://github.com/yumorishita/LiCSBAS/issues/295

The cause of the error is 
- The number of interferograms is too small
- Too many unwrapping errors are included

Try
- change p11_unw_thre, p11_coh_thre, and/or p12_loop_thre
- crop the area by step05
- improve unwrapping quality and/or increase unwrapped data if you created them manually

**Comment by marchelgamaliel** [comment]
thank you sir for your response, can you give me some explanation of the variable p11_unw_thre, p11_coh_thre, and/or p12_loop_thre?

**Comment by yumorishita** [comment]
About reference point: https://github.com/yumorishita/LiCSBAS/issues/102, https://github.com/yumorishita/LiCSBAS/issues/266

**Comment by yumorishita** [comment]
```
LiCSBAS04op_mask_unw.py ver1.3.5 20210105 Y. Morishita
LiCSBAS04op_mask_unw.py -i GEOCml1 -o GEOCml1mask -c 0.1
LiCSBAS/bin/LiCSBAS04op_mask_unw.py:176: FutureWarning: In the future np.bool will be defined as the corresponding NumPy scalar.
bool_mask = np.zeros((length, width), dtype=np.bool)
Traceback (most recent call last):
File "LiCSBAS/bin/LiCSBAS04op_mask_unw.py", line 326, in
sys.exit(main())
^^^^^^
File "LiCSBAS/bin/LiCSBAS04op_mask_unw.py", line 176, in main
bool_mask = np.zeros((length, width), dtype=np.bool)
^^^^^^^
File "miniconda3/envs/licsbas/lib/python3.11/site-packages/numpy/init.py", line 324, in getattr
raise AttributeError(former_attrs[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
np.bool was a deprecated alias for the builtin bool. To avoid this error in existing code, use bool by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use np.bool_ here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
```

https://github.com/yumorishita/LiCSBAS/issues/307#issuecomment-1798388036

**Comment by yumorishita** [comment]
LiCSBAS_plot_ts.py and LiCSBAS_cum2vel.py
```
...
Reading TS_GEOCml1clip/cum_filt.h5
Traceback (most recent call last):
File "LiCSBAS/bin/LiCSBAS_plot_ts.py", line 363, in
refx1, refx2, refy1, refy2 = [int(s) for s in re.split('[:/]', refarea)]
File "re.py", line 231, in split
return _compile(pattern, flags).split(string, maxsplit)
TypeError: cannot use a string pattern on a bytes-like object
```

Modify 
`refarea = cumh5['refarea'][()] ` to `refarea = cumh5['refarea'][()].decode('utf-8')`

https://github.com/yumorishita/LiCSBAS/issues/40
https://github.com/yumorishita/LiCSBAS/issues/65
https://github.com/yumorishita/LiCSBAS/issues/96

**Comment by yumorishita** [comment]
```
Searching latest epoch for mli...
Traceback (most recent call last):
File "LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 500, in
sys.exit(main())
^^^^^^
File "LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 213, in main
response = requests.get(url)
^^^^^^^^^^^^^^^^^
File "miniconda3/envs/licsbas/lib/python3.12/site-packages/requests/api.py", line 73, in get
return request("get", url, params=params, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "miniconda3/envs/licsbas/lib/python3.12/site-packages/requests/api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "miniconda3/envs/licsbas/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
resp = self.send(prep, **send_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "miniconda3/envs/licsbas/lib/python3.12/site-packages/requests/sessions.py", line 725, in send
history = [resp for resp in gen]
^^^^^^^^^^^^^^^^^^^^^^
File "miniconda3/envs/licsbas/lib/python3.12/site-packages/requests/sessions.py", line 191, in resolve_redirects
raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

The bug was fixed in LiCSBAS2 (https://github.com/yumorishita/LiCSBAS2/pull/55). Please use LiCSBAS2 or apply the fix in your local LiCSBAS script.

**Comment by yumorishita** [comment]
What are vel(1) and vel(2) in LiCSBAS_plot_ts.py?

They correspond to cum*.h5 files indicated by -i and --i2 options. By default vel(1) and vel(2) are velocities of filtered and unfiltered time series, respectively.

https://github.com/yumorishita/LiCSBAS/issues/117#issuecomment-878956383

**Comment by yumorishita** [comment]
Cannot download files or the downloading speed is slow in LiCSBAS01_get_geotiff.py.

It could be because of LiCSAR server maintenance and there is nothing to do from the LiCSBAS side. Please contact COMET.
https://comet.nerc.ac.uk/comet-lics-portal/
comet@leeds.ac.uk

**Comment by MIEMESSI** [comment]
Dear Professor, can LICSBAS process cc and unw data processed by envi

**Comment by yumorishita** [comment]
Yes, as long as you prepare the files with the correct format for LiCSBAS.
https://github.com/yumorishita/LiCSBAS/wiki/file_structure#input-for-step-1-1-or-steps-0-3-to-0-5-output-of-step-0-2

**Comment by MIEMESSI** [comment]
Hello Professor, I would like to ask, as shown in the figure, the bottom picture is the rate image processed by licsbas, and the left picture is the image processed by envi, but their resolutions are different, but their input image resolutions are the same. I would like to ask, is it the setting of licsbas parameter that leads to the different resolution of the final output image
![image](https://github.com/user-attachments/assets/622f9e0c-a7ba-4912-9460-cd1583a85b8c)
![image](https://github.com/user-attachments/assets/2e6a1703-972e-49eb-b76b-68b6d934249d)

**Comment by yumorishita** [comment]
If you are using the [COMET version LiCSBAS](https://github.com/comet-licsar/LiCSBAS), I cannot support it. Please report any issues to its repository.

**Comment by shabiss** [comment]
Dear professor,how can i change the ref_area to get velocity after i complete all steps?

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1964088205

**Comment by pratanu9083** [comment]
> Unfortunately, I cannot update this LiCSBAS repository for a reason. All known issues are solved in [LiCSBAS2](https://github.com/yumorishita/LiCSBAS2) and it will keep updated. I recommend using LiCSBAS2 if you encounter an issue.

How to update LiCSBAS to LiCSBAS2?

**Comment by yumorishita** [comment]
> How to update LiCSBAS to LiCSBAS2?

Remove LiCSABS and install LiCSBAS2.

**Comment by pratanu9083** [comment]
Dear Professor,

Thank you for your answer.

I am not able to find the instructions for installing LiCSBAS2.

Can you please provide ?

**Comment by yumorishita** [comment]
Same as LiCSBAS.

**Comment by pratanu9083** [comment]
Dear Professor,

I only found one installation process. ( mentoned in the link: https://github.com/yumorishita/LiCSBAS/wiki/1_Installation)

And if the instruction is same, what is the difference between licsbas and licsbas2 installation?

Please help me to install licsbas2.

**Comment by yumorishita** [comment]
Replace `git clone https://github.com/yumorishita/LiCSBAS.git` with `git clone https://github.com/yumorishita/LiCSBAS2.git`.

**Comment by adillahana** [comment]
Dear Professor,
I found an error that saying this:

Traceback (most recent call last):
  File "/home/darmasanjaya/LiCSBAS2/bin/LiCSBAS03op_GACOS.py", line 549, in <module>
    sys.exit(main())
  File "/home/darmasanjaya/LiCSBAS2/bin/LiCSBAS03op_GACOS.py", line 368, in main
    plot_lib.plot_gacos_info(gacinfofile, pngfile)
  File "/home/darmasanjaya/LiCSBAS2/LiCSBAS_lib/LiCSBAS_plot_lib.py", line 152, in plot_gacos_info
    xylim1 = np.max(np.concatenate((std_bf, std_af)))+1
  File "<__array_function__ internals>", line 180, in amax
  File "/home/darmasanjaya/miniconda3/envs/adillahana/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2791, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/home/darmasanjaya/miniconda3/envs/adillahana/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

How could i solve it? Thank you Prof

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/252
https://github.com/yumorishita/LiCSBAS/issues/120
https://github.com/yumorishita/LiCSBAS/issues/87

**Comment by adillahana** [comment]
Those problem was solved. Thank you, Prof

But now, i have a problem to plot that saying this:
LiCSBAS_plot_ts.py -i TS_GEOCml1GACOSmaskclip/cum_filt.h5

Reading TS_GEOCml1GACOSmaskclip/cum_filt.h5
Reading TS_GEOCml1GACOSmaskclip/cum.h5 as 2nd
Reading mask
/home/adillahana/LiCSBAS2/bin/LiCSBAS_plot_ts.py:418: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
  inc_agl_deg = np.rad2deg(np.arccos(LOSu))
Reading mask
Reading coh_avg
Reading n_unw
Reading vstd
Reading maxTlen
Reading n_gap
Reading stc
Reading n_ifg_noloop
Reading n_loop_err
Reading resid_rms
Reading slc.mli
Reading hgt
/home/adillahana/LiCSBAS2/bin/LiCSBAS_plot_ts.py:456: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
  refvalue_vel = np.nanmean((vel*mask)[refy1:refy2+1, refx1:refx2+1])
/home/adillahana/LiCSBAS2/bin/LiCSBAS_plot_ts.py:457: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
  vmin_auto = np.nanpercentile(vel*mask, 100-auto_crange)
/home/adillahana/LiCSBAS2/bin/LiCSBAS_plot_ts.py:458: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
  vmax_auto = np.nanpercentile(vel*mask, auto_crange)
/home/adillahana/LiCSBAS2/bin/LiCSBAS_plot_ts.py:482: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
  data = vel*mask-np.nanmean((vel*mask)[refy1:refy2+1, refx1:refx2+1])
Traceback (most recent call last):
  File "/home/adillahana/LiCSBAS2/bin/LiCSBAS_plot_ts.py", line 843, in <module>
    printcoords(lastevent)
  File "/home/adillahana/LiCSBAS2/bin/LiCSBAS_plot_ts.py", line 734, in printcoords
    pax2.set_data(jj, ii)
  File "/home/adillahana/miniconda3/envs/hana/lib/python3.11/site-packages/matplotlib/lines.py", line 665, in set_data
    self.set_xdata(x)
  File "/home/adillahana/miniconda3/envs/hana/lib/python3.11/site-packages/matplotlib/lines.py", line 1289, in set_xdata
    raise RuntimeError('x must be a sequence')
RuntimeError: x must be a sequence
^C
[1]+  Exit 1                  LiCSBAS_plot_ts.py -i TS_GEOCml1GACOSmaskclip/cum_filt.h5

How could i solve it?

**Comment by adillahana** [comment]
Hii Prof.. I have an issue when running the batch script that stop in this step for a long time. I've made sure that connection and storage is okay. How could i solve this? Thank you Prof.


Elapsed time: 00h 00m 23s

LiCSBAS02_ml_prep.py Successfully finished!!

Output directory: GEOCml1


LiCSBAS03op_GACOS.py ver1.5.5 20201119 Y. Morishita
LiCSBAS03op_GACOS.py -i GEOCml1 -o GEOCml1GACOS --fillhole

Convert ztd/sltd.geo.tif files to sltd.geo files...
  8 parallel processing...
  Finished    0/   9th sltd...
    Use 20181007.sltd.geo.tif
    Use 20181031.sltd.geo.tif
    Use 20181019.sltd.geo.tif
    Use 20181112.sltd.geo.tif
    Use 20181206.sltd.geo.tif
    Use 20181218.sltd.geo.tif
    Use 20181230.sltd.geo.tif
    Use 20181124.sltd.geo.tif
    Use 20190111.sltd.geo.tif

Correct unw data...
  8 parallel processing...
  Finished    0/  21th unw...
  Finished   10/  21th unw...
  Finished   20/  21th unw...

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1500877478

**Comment by yumorishita** [comment]
Module versions I have confirmed:
https://github.com/yumorishita/LiCSBAS/issues/441#issuecomment-2592781864

Python3.10
```
# Name                    Version                   Build  Channel
astropy                   5.1             py310ha9d4c09_0  
beautifulsoup4            4.11.1          py310h06a4308_0  
gdal                      3.4.1           py310h8f0303e_0  
h5py                      3.7.0           py310he06866b_0  
matplotlib                3.7.0           py310h06a4308_0  
numpy                     1.23.5          py310hd5efca6_0  
psutil                    5.9.0           py310h5eee18b_0  
python                    3.10.9               h7a1cb2a_0  
requests                  2.28.1          py310h06a4308_0  
shapely                   1.8.4           py310h81ba7c5_0  
statsmodels               0.13.5          py310ha9d4c09_0  
```

Python3.11
```
# Name                    Version                   Build  Channel
astropy                   5.1             py311hbed6279_0  
beautifulsoup4            4.12.2          py311h06a4308_0  
gdal                      3.6.2           py311h4618797_1  
h5py                      3.7.0           py311h021c08c_0  
matplotlib                3.7.1           py311h06a4308_1  
numpy                     1.24.3          py311hc206e33_0  
psutil                    5.9.0           py311h5eee18b_0  
python                    3.11.3               h7a1cb2a_0  
requests                  2.29.0          py311h06a4308_0  
shapely                   2.0.1           py311h24a2a10_0  
statsmodels               0.13.5          py311h5eee18b_1  
```

**Comment by Geralda02** [comment]
Elapsed time: 06h 17m 10s

LiCSBAS01_get_geotiff.py Successfully finished!!

Output directory: /mnt/c/Pengolahan2/098A_09673_121312/GEOC

LiCSBAS02_ml_prep.py ver1.7.4 20201119 Y. Morishita
LiCSBAS02_ml_prep.py -i GEOC -n 1

Create E.geo
E.geo created

Create N.geo
N.geo created

Create U.geo
U.geo created

Create slc.mli
slc.mli[.png] created

Create hgt
hgt[.png] created

Create unw and cc
12 parallel processing...
0/1368th IFG...
290/1368th IFG...
30/1368th IFG...
320/1368th IFG...
60/1368th IFG...
90/1368th IFG...
120/1368th IFG...
150/1368th IFG...
300/1368th IFG...
180/1368th IFG...
210/1368th IFG...
270/1368th IFG...
240/1368th IFG...
10/1368th IFG...
40/1368th IFG...
330/1368th IFG...
130/1368th IFG...
70/1368th IFG...
310/1368th IFG...
100/1368th IFG...
220/1368th IFG...
160/1368th IFG...
280/1368th IFG...
190/1368th IFG...
250/1368th IFG...
20/1368th IFG...
50/1368th IFG...
340/1368th IFG...
140/1368th IFG...
110/1368th IFG...
80/1368th IFG...
350/1368th IFG...
230/1368th IFG...
260/1368th IFG...
170/1368th IFG...
380/1368th IFG...
200/1368th IFG...
580/1368th IFG...
610/1368th IFG...
410/1368th IFG...
640/1368th IFG...
440/1368th IFG...
670/1368th IFG...
470/1368th IFG...
560/1368th IFG...
360/1368th IFG...
390/1368th IFG...
500/1368th IFG...
530/1368th IFG...
570/1368th IFG...
620/1368th IFG...
680/1368th IFG...
420/1368th IFG...
480/1368th IFG...
590/1368th IFG...
650/1368th IFG...
450/1368th IFG...
510/1368th IFG...
700/1368th IFG...
540/1368th IFG...
370/1368th IFG...
730/1368th IFG...
690/1368th IFG...
600/1368th IFG...
630/1368th IFG...
430/1368th IFG...
760/1368th IFG...
660/1368th IFG...
490/1368th IFG...
460/1368th IFG...
710/1368th IFG...
740/1368th IFG...
550/1368th IFG...
790/1368th IFG...
870/1368th IFG...
900/1368th IFG...
770/1368th IFG...
930/1368th IFG...
960/1368th IFG...
850/1368th IFG...
990/1368th IFG...
880/1368th IFG...
820/1368th IFG...
720/1368th IFG...
910/1368th IFG...
940/1368th IFG...
1020/1368th IFG...
800/1368th IFG...
970/1368th IFG...
750/1368th IFG...
860/1368th IFG...
780/1368th IFG...
1000/1368th IFG...
890/1368th IFG...
920/1368th IFG...
1030/1368th IFG...
950/1368th IFG...
830/1368th IFG...
980/1368th IFG...
1050/1368th IFG...
1010/1368th IFG...
1160/1368th IFG...
1080/1368th IFG...
1110/1368th IFG...
1190/1368th IFG...
1140/1368th IFG...
1040/1368th IFG...
810/1368th IFG...
840/1368th IFG...
1060/1368th IFG...
1220/1368th IFG...
1170/1368th IFG...
1090/1368th IFG...
1120/1368th IFG...
1200/1368th IFG...
1150/1368th IFG...
1250/1368th IFG...
1280/1368th IFG...
1070/1368th IFG...
1180/1368th IFG...
1100/1368th IFG...
1130/1368th IFG...
1310/1368th IFG...
1210/1368th IFG...
1340/1368th IFG...
1230/1368th IFG...
1260/1368th IFG...
1290/1368th IFG...
1320/1368th IFG...
1240/1368th IFG...
1270/1368th IFG...
1300/1368th IFG...
1330/1368th IFG...

The honorable, why am i stuck in this process? and always can't continue the processing? what is the solution?

**Comment by yumorishita** [comment]
```
File "LiCSBAS/LiCSBAS_lib/LiCSBAS_io_lib.py", line 199, in read_img
data = np.fromfile(file, dtype=dtype).reshape((length, width))
ValueError: cannot reshape array of size XXX into shape (X,X)
```

Some of the GEOCml\*/\*/\*.unw or *.cc files are corrupted. They all must have the same file size.
Please remove files with inconsistent size or entire GEOCml*, and rerun from a previous step (e.g., step02).

https://github.com/yumorishita/LiCSBAS/issues/474
https://github.com/yumorishita/LiCSBAS/issues/399
https://github.com/yumorishita/LiCSBAS/issues/307
https://github.com/yumorishita/LiCSBAS/issues/269
https://github.com/yumorishita/LiCSBAS/issues/194
https://github.com/yumorishita/LiCSBAS/issues/154
