### ISSUE TITLE
Error after run LiCSBAS03op_GACOS.py -i GEOCml1 -o GEOC_CACOS -g GACOS 

### ISSUE THREAD

**Issue by sdlccug** [yumorishita/LiCSBAS#248]
LiCSBAS03op_GACOS.py ver1.5.5 20201119 Y. Morishita
LiCSBAS03op_GACOS.py -i GEOCml1 -o GEOC_CACOS -g GACOS

Convert ztd/sltd.geo.tif files to sltd.geo files...
  121/121 sltd already exist. Skip

Correct unw data...
  419/424 corrected unw already exist. Skip
  5 parallel processing...
  Finished    0/   5th unw...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/mnt/rfchen/tools/miniconda3/envs/licsbas/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/mnt/rfchen/tools/miniconda3/envs/licsbas/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/mnt/rfchen/licSBSA/LiCSBAS-master/bin/LiCSBAS03op_GACOS.py", line 519, in correct_wrapper
    unw = io_lib.read_img(unwfile, length_unw, width_unw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/rfchen/licSBSA/LiCSBAS-master/LiCSBAS_lib/LiCSBAS_io_lib.py", line 199, in read_img
    data = np.fromfile(file, dtype=dtype).reshape((length, width))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 8322942 into shape (2715,3174)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/rfchen/licSBSA/LiCSBAS-master/bin/LiCSBAS03op_GACOS.py", line 550, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/rfchen/licSBSA/LiCSBAS-master/bin/LiCSBAS03op_GACOS.py", line 353, in main
    _return = p.map(correct_wrapper, range(n_ifg2))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/rfchen/tools/miniconda3/envs/licsbas/lib/python3.11/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/rfchen/tools/miniconda3/envs/licsbas/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
ValueError: cannot reshape array of size 8322942 into shape (2715,3174)

**Comment by yumorishita** [comment]
Please use batch_LiCSBAS.sh and attach the full log.

**Comment by rafiqiaria** [comment]
Hello, Mr. @yumorishita. i'm having the identical problem as Mr. @cugchenrufan here i attached my full log. Btw, i'm using the batch_LiCSBAS.sh to run my process, but there are certain parameters being modified. Thanks in advance.
[202305241627batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/11553960/202305241627batch_LiCSBAS_01_16.log)
