### ISSUE TITLE
error in  LiCSBAS11_check_unw.py -d GEOCml1

### ISSUE THREAD

**Issue by sajid-zaman** [yumorishita/LiCSBAS#273]
I am processing the data for Chaman Fault in western Pakistan, but there is an error in LiCSBAS11_check_unw.py 
[t.txt](https://github.com/yumorishita/LiCSBAS/files/12206545/t.txt)
Here i try to process different area images, but have same issue, please help to find issue. 
(licsbas) sajid@LAPTOP-0BVHFV8E:/mnt/d/MACD/137A_04835_131313$ LiCSBAS11_check_unw.py -d GEOCml1>t.txt
Traceback (most recent call last):
  File "/mnt/d/MACD/042A_05933_131313/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 356, in <module>
    sys.exit(main())
  File "/mnt/d/MACD/042A_05933_131313/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 331, in main
    plot_lib.plot_network(ifgdates, bperp, [], pngfile)
  File "/mnt/d/MACD/042A_05933_131313/LiCSBAS/LiCSBAS_lib/LiCSBAS_plot_lib.py", line 285, in plot_network
    ax.grid(b=True, which='major')
  File "/home/sajid/miniconda3/envs/licsbas/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 3194, in grid
    self.xaxis.grid(visible, which=which, **kwargs)
  File "/home/sajid/miniconda3/envs/licsbas/lib/python3.9/site-packages/matplotlib/axis.py", line 1660, in grid
    self.set_tick_params(which='major', **gridkw)
  File "/home/sajid/miniconda3/envs/licsbas/lib/python3.9/site-packages/matplotlib/axis.py", line 932, in set_tick_params
    kwtrans = self._translate_tick_params(kwargs)
  File "/home/sajid/miniconda3/envs/licsbas/lib/python3.9/site-packages/matplotlib/axis.py", line 1076, in _translate_tick_params
    raise ValueError(
ValueError: keyword grid_b is not recognized; valid keywords are ['size', 'width', 'color', 'tickdir', 'pad', 'labelsize', 'labelcolor', 'zorder', 'gridOn', 'tick1On', 'tick2On', 'label1On', 'label2On', 'length', 'direction', 'left', 'bottom', 'right', 'top', 'labelleft', 'labelbottom', 'labelright', 'labeltop', 'labelrotation', 'grid_agg_filter', 'grid_alpha', 'grid_animated', 'grid_antialiased', 'grid_clip_box', 'grid_clip_on', 'grid_clip_path', 'grid_color', 'grid_dash_capstyle', 'grid_dash_joinstyle', 'grid_dashes', 'grid_data', 'grid_drawstyle', 'grid_figure', 'grid_fillstyle', 'grid_gapcolor', 'grid_gid', 'grid_in_layout', 'grid_label', 'grid_linestyle', 'grid_linewidth', 'grid_marker', 'grid_markeredgecolor', 'grid_markeredgewidth', 'grid_markerfacecolor', 'grid_markerfacecoloralt', 'grid_markersize', 'grid_markevery', 'grid_mouseover', 'grid_path_effects', 'grid_picker', 'grid_pickradius', 'grid_rasterized', 'grid_sketch_params', 'grid_snap', 'grid_solid_capstyle', 'grid_solid_joinstyle', 'grid_transform', 'grid_url', 'grid_visible', 'grid_xdata', 'grid_ydata', 'grid_zorder', 'grid_aa', 'grid_c', 'grid_ds', 'grid_ls', 'grid_lw', 'grid_mec', 'grid_mew', 'grid_mfc', 'grid_mfcalt', 'grid_ms']

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1498886957

**Comment by khakim** [comment]
Dear Yumorishita,

I have the same problem with LiCSBAS11_check_unw.py as below:

LiCSBAS11_check_unw.py ver1.3.3 20210402 Y. Morishita
LiCSBAS11_check_unw.py -d GEOCml1

coh_thre     : 0.05
unw_cov_thre : 0.3
Traceback (most recent call last):
  File "/usr/local/LiCSBAS2/bin/LiCSBAS11_check_unw.py", line 356, in <module>
    sys.exit(main())
  File "/usr/local/LiCSBAS2/bin/LiCSBAS11_check_unw.py", line 175, in main
    width = int(io_lib.get_param_par(mlipar, 'range_samples'))
  File "/usr/local/LiCSBAS2/LiCSBAS_lib/LiCSBAS_io_lib.py", line 236, in get_param_par
    value = subp.check_output(['grep', field,mlipar]).decode().split()[1].strip()
  File "/home/khakim/anaconda3/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/khakim/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['grep', 'range_samples', ... /GEOCml1/slc.mli.par']' returned non-zero exit status 1.

Please help to solve it.

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/97#issuecomment-2006975659

**Comment by luluksabdubusoroh** [comment]
Dear Yumorishita, I have problem with LiCSBAS11_check_unw.py

LiCSBAS11_check_unw.py ver1.3.3 20210402 Y. Morishita
LiCSBAS11_check_unw.py -d GEOCml1clip

coh_thre     : 0.05
unw_cov_thre : 0.3

Size         : 191 x 121

Reading unw and cc data...
    0/ 45th unw to identify valid area...
    0/ 45th cc and unw...

0/45 ifgs are discarded from further processing.
ifg dates        unw_cov coh_av
Traceback (most recent call last):
  File "/root/SBAS/LiCSBAS2/bin/LiCSBAS11_check_unw.py", line 356, in <module>
    sys.exit(main())
             ~~~~^^
  File "/root/SBAS/LiCSBAS2/bin/LiCSBAS11_check_unw.py", line 331, in main
    plot_lib.plot_network(ifgdates, bperp, [], pngfile)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SBAS/LiCSBAS2/LiCSBAS_lib/LiCSBAS_plot_lib.py", line 309, in plot_network
    plt.savefig(pngfile)
    ~~~~~~~~~~~^^^^^^^^^
  File "/root/miniconda3/envs/licsbas/lib/python3.13/site-packages/matplotlib/pyplot.py", line 1243, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/root/miniconda3/envs/licsbas/lib/python3.13/site-packages/matplotlib/figure.py", line 3490, in savefig
    self.canvas.print_figure(fname, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/licsbas/lib/python3.13/site-packages/matplotlib/backend_bases.py", line 2184, in print_figure
    result = print_method(
        filename,
    ...<3 lines>...
        bbox_inches_restore=_bbox_inches_restore,
        **kwargs)
  File "/root/miniconda3/envs/licsbas/lib/python3.13/site-packages/matplotlib/backend_bases.py", line 2040, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
                                                                 ~~~~^
        *args, **{k: v for k, v in kwargs.items() if k not in skip}))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/licsbas/lib/python3.13/site-packages/matplotlib/backends/backend_agg.py", line 481, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/licsbas/lib/python3.13/site-packages/matplotlib/backends/backend_agg.py", line 429, in _print_pil
    FigureCanvasAgg.draw(self)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/root/miniconda3/envs/licsbas/lib/python3.13/site-packages/matplotlib/backends/backend_agg.py", line 382, in draw
    self.figure.draw(self.renderer)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/licsbas/lib/python3.13/site-packages/matplotlib/artist.py", line 94, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/root/miniconda3/envs/licsbas/lib/python3.13/site-packages/matplotlib/artist.py", line 71, in draw_wrapper
    return draw(artist, renderer)
  File "/root/miniconda3/envs/licsbas/lib/python3.13/site-packages/matplotlib/figure.py", line 3257, in draw
    mimage._draw_list_compositing_images(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        renderer, self, artists, self.suppressComposite)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/licsbas/lib/python3.13/site-packages/matplotlib/image.py", line 134, in _draw_list_compositing_images
    a.draw(renderer)
    ~~~~~~^^^^^^^^^^
  File "/root/miniconda3/envs/licsbas/lib/python3.13/site-packages/matplotlib/artist.py", line 71, in draw_wrapper
    return draw(artist, renderer)
  File "/root/miniconda3/envs/licsbas/lib/python3.13/site-packages/matplotlib/axes/_base.py", line 3181, in draw
    mimage._draw_list_compositing_images(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        renderer, self, artists, self.get_figure(root=True).suppressComposite)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/licsbas/lib/python3.13/site-packages/matplotlib/image.py", line 134, in _draw_list_compositing_images
    a.draw(renderer)
    ~~~~~~^^^^^^^^^^
  File "/root/miniconda3/envs/licsbas/lib/python3.13/site-packages/matplotlib/artist.py", line 71, in draw_wrapper
    return draw(artist, renderer)
  File "/root/miniconda3/envs/licsbas/lib/python3.13/site-packages/matplotlib/axis.py", line 1415, in draw
    ticks_to_draw = self._update_ticks()
  File "/root/miniconda3/envs/licsbas/lib/python3.13/site-packages/matplotlib/axis.py", line 1293, in _update_ticks
    major_labels = self.major.formatter.format_ticks(major_locs)
  File "/root/miniconda3/envs/licsbas/lib/python3.13/site-packages/matplotlib/dates.py", line 799, in format_ticks
    if (self._locator.axis and
        ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'axis'
(licsbas) root@DESKTOP-JAUGST0:/mnt/d/licsbas/124D_04854_171313#

please help to solve it

**Comment by benjamin-kettleb** [comment]
I am also getting the same issue for the 1. steps when it comes to saving figures!!

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/444#issuecomment-2618795475
