### ISSUE TITLE
LiCSBAS11_check_unw.py -d GEOCml1/

### ISSUE THREAD

**Issue by sajid-zaman** [yumorishita/LiCSBAS#277]
I got this error aftr running "LiCSBAS11_check_unw.py -d GEOCml1/", How can i resolve this issue?

@DESKTOP-IB0AUID:/mnt/f/MACD/042A_06133_131313$ LiCSBAS11_check_unw.py -d GEOCml1/

LiCSBAS11_check_unw.py ver1.3.3 20210402 Y. Morishita
LiCSBAS11_check_unw.py -d GEOCml1/

coh_thre     : 0.05
unw_cov_thre : 0.3

Size         : 3032 x 2701
Traceback (most recent call last):
  File "/mnt/f/MACD/042A_06133_131313/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 356, in <module>
    sys.exit(main())
  File "/mnt/f/MACD/042A_06133_131313/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 182, in main
    shutil.copy(os.path.join(ifgdir, file), infodir)
  File "/home/sajid/miniconda3/envs/licsbas/lib/python3.9/shutil.py", line 416, in copy
    copymode(src, dst, follow_symlinks=follow_symlinks)
  File "/home/sajid/miniconda3/envs/licsbas/lib/python3.9/shutil.py", line 305, in copymode
    chmod_func(dst, stat.S_IMODE(st.st_mode))
PermissionError: [Errno 1] Operation not permitted: '/mnt/f/MACD/042A_06133_131313/TS_GEOCml1/info/slc.mli.par'
[step11.txt](https://github.com/yumorishita/LiCSBAS/files/12249844/step11.txt)

**Comment by yumorishita** [comment]
PermissionError is caused by your enviromentnal setting, not LiCSBAS. Please check your enviroment. Maybe working in /home/sajid/ instead of /mnt/f might solve the problem.
