### ISSUE TITLE
I keep getting this error when i am doing batch_LiCSBAS.sh 

### ISSUE THREAD

**Issue by nssuthar16** [yumorishita/LiCSBAS#283]
Traceback (most recent call last):
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f60f6e38ed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gws-access.jasmin.ac.uk', port=443): Max retries exceeded with url: /public/nceo_geohazards/LiCSAR_products/129/129A_05935_131313/interferograms/20221101_20221113/20221101_20221113.geo.unw.tif (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f60f6e38ed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/home/neeraj/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 455, in check_exist_wrapper
    rc = tools_lib.comp_size_time(url_data, path_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neeraj/LiCSBAS/LiCSBAS_lib/LiCSBAS_tools_lib.py", line 74, in comp_size_time
    response = requests.head(file_remote, allow_redirects=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/site-packages/requests/api.py", line 100, in head
    return request("head", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/site-packages/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/site-packages/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/site-packages/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
           ^^^^^^^^^^
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gws-access.jasmin.ac.uk', port=443): Max retries exceeded with url: /public/nceo_geohazards/LiCSAR_products/129/129A_05935_131313/interferograms/20221101_20221113/20221101_20221113.geo.unw.tif (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f60f6e38ed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/neeraj/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 499, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/neeraj/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 351, in main
    rc = p.map(check_exist_wrapper, args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neeraj/.pyenv/versions/miniconda3-latest/envs/licsbas/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
requests.exceptions.ConnectionError: None: Max retries exceeded with url: /public/nceo_geohazards/LiCSAR_products/129/129A_05935_131313/interferograms/20221101_20221113/20221101_20221113.geo.unw.tif (Caused by None)

**Comment by yumorishita** [comment]
Maybe there was a network issue. Please try again.
