### ISSUE TITLE
ValueError in LiCSBAS11_check_unw.py

### ISSUE THREAD

**Issue by SingyuTang** [yumorishita/LiCSBAS#298]
When I executed the LiCSBAS11_check_unw.py command, the parameters I set were all default parameters, and the following error occurred:
Traceback (most recent call last):
   File "/usr/local/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 356, in <module>
     sys.exit(main())
   File "/usr/local/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 311, in main
     raise ValueError('All ifgs are regarded as bad!\nChange the parameters or check the input ifgs.\n')
ValueError: All ifgs are regarded as bad!
Change the parameters or check the input ifgs.

Please tell me what is causing this and how can I avoid this error.

**Comment by yumorishita** [comment]
As the error message said, you should change the parameters or check the input ifgs.
If you need a more detailed explanation, please attach the full log and `info/11ifg_stats.txt`.

**Comment by SingyuTang** [comment]
My info/11ifg_stats.txt file is attached, and my command parameter settings and console output are as follows:

The command I entered was：”LiCSBAS11_check_unw.py -d GEOCmli -t TS_GEOCmli -c 0.05 -u 0.3“

The console output is：
“LiCSBAS11_check_unw.py ver1.3.3 20210402 Y. Morishita
LiCSBAS11_check_unw.py -d GEOCmli -t TS_GEOCmli -c 0.05 -u 0.3

coh_thre     : 0.05
unw_cov_thre : 0.3

Size         : 3428 x 2623

Reading unw and cc data...
    0/238th unw to identify valid area...
/usr/local/LiCSBAS/bin/LiCSBAS11_check_unw.py:204: RuntimeWarning: invalid value encountered in equal
  unw[unw == 0] = np.nan # Fill 0 with nan
  100/238th unw to identify valid area...
  200/238th unw to identify valid area...
    0/238th cc and unw...
/usr/local/LiCSBAS/bin/LiCSBAS11_check_unw.py:219: RuntimeWarning: invalid value encountered in equal
  unw[unw == 0] = np.nan # Fill 0 with nan
/home/root123/anaconda3/envs/licsbas/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/home/root123/anaconda3/envs/licsbas/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
  100/238th cc and unw...
  200/238th cc and unw...

238/238 ifgs are discarded from further processing.
ifg dates        unw_cov coh_av
20210823_20210904  0.996    nan
20210823_20210916  0.996    nan
20210823_20210928  0.996    nan
...
...
20230521_20230602  0.996    nan
20230521_20230614  0.996    nan
20230602_20230614  0.996    nan

Traceback (most recent call last):
  File "/usr/local/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 356, in <module>
    sys.exit(main())
  File "/usr/local/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 311, in main
    raise ValueError('All ifgs are regarded as bad!\nChange the parameters or check the input ifgs.\n')
ValueError: All ifgs are regarded as bad!
Change the parameters or check the input ifgs.”

Do you think what is the problem that caused this error?How should I modify it? Thanks.

[11ifg_stats.txt](https://github.com/yumorishita/LiCSBAS/files/12793656/11ifg_stats.txt)

**Comment by yumorishita** [comment]
The reason for the error is that all the coherence images have no valid values. How did you get the coherence images?

**Comment by SingyuTang** [comment]
My coherence images and unwrapped images are obtained through GAMMA software. I think your program can better help me select interference pairs. I guess in theory this is possible.

**Comment by yumorishita** [comment]
Please check your coherence images were correctly created.

**Comment by edcpengz** [comment]
I also encountered the same problem, how did you finally solve it? @SingyuTang
