### ISSUE TITLE
I am facing the Download error

### ISSUE THREAD

**Issue by vis2hnu1** [yumorishita/LiCSBAS#324]
Dear @yumorishita sir,

I had successfully installed LiCSBAS and got the message "LiCSBAS install  is Ok", But after running the ./batch_LiCSBAS.sh, I am facing this error. Could you please let on know how to rectify this error sir. 

Thanking you sir,

![image](https://github.com/yumorishita/LiCSBAS/assets/108609251/498f46a6-b546-41cb-8d25-1470bc6d2b7c)

**Comment by yumorishita** [comment]
It is probably due to the LiCS server-side issue because I cannot access https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/124/124D_04854_171313/. Please try again later.

**Comment by vis2hnu1** [comment]
Okay sir. I will try it later.

Thanking  you sir,

**Comment by vis2hnu1** [comment]
Dear @yumorishita sir,

When the LiCS server-side issue can be resolved sir, please let me know sir.

Thank you sir.

**Comment by yumorishita** [comment]
It seems the server issue has been solved. Please try again.

**Comment by vis2hnu1** [comment]
Dear @yumorishita sir,
I am not able to successfully complete the 16 step sir. It is showing like what I attached as figure, It is kept running from very long time sir. Sir, please let me know sir how to complete this step.
![image](https://github.com/yumorishita/LiCSBAS/assets/108609251/5d822984-8423-48af-85a2-150ea1262519)

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1500877478

**Comment by vis2hnu1** [comment]
Thank you sir, It worked.

> [#244 (comment)](https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1500877478)

**Comment by Geralda02** [comment]
Good afternoon, the honorable. May I ask, why did I get an error like this at the beginning of processing, sir? Is there a solution, sir? Thank you, sir.


(licsbas) geralda123@Geralda:/mnt/c/Pengolahan3bln/047D_09652_111009$ ./batch_LiCSBAS.sh

Start step: 01
End step:   16
Log file:   log/202505101442batch_LiCSBAS_01_16.log


LiCSBAS01_get_geotiff.py ver1.6.5 20240607 Y. Morishita
LiCSBAS01_get_geotiff.py -s 20150101 -e 2020131 --get_gacos

Frame ID is 047D_09652_111009

Download 047D_09652_111009.geo.E.tif
    047D_09652_111009.geo.E.tif, 16.72MB, 34s, 503.63KB/s
Download 047D_09652_111009.geo.N.tif
    047D_09652_111009.geo.N.tif, 16.72MB, 35s, 489.25KB/s
Download 047D_09652_111009.geo.U.tif
    047D_09652_111009.geo.U.tif, 16.72MB, 30s, 570.78KB/s
Download 047D_09652_111009.geo.hgt.tif
    ChunkedEncodingError for 047D_09652_111009.geo.hgt.tif in 1th try
    SSLError for 047D_09652_111009.geo.hgt.tif in 2th try
    SSLError for 047D_09652_111009.geo.hgt.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/47/047D_09652_111009/metadata/047D_09652_111009.geo.hgt.tif

Download baselines
    SSLError for baselines in 1th try
    SSLError for baselines in 2th try
    SSLError for baselines in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/47/047D_09652_111009/metadata/baselines
Download network.png
    SSLError for network.png in 1th try
    SSLError for network.png in 2th try
    SSLError for network.png in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/47/047D_09652_111009/metadata/network.png
Download metadata.txt
    SSLError for metadata.txt in 1th try
    SSLError for metadata.txt in 2th try
    SSLError for metadata.txt in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/47/047D_09652_111009/metadata/metadata.txt

Searching latest epoch for mli...
Traceback (most recent call last):
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/site-packages/urllib3/connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/site-packages/urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/ssl.py", line 1319, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gws-access.jasmin.ac.uk', port=443): Max retries exceeded with url: /public/nceo_geohazards/LiCSAR_products/47/047D_09652_111009/epochs/ (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geralda123/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 502, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/geralda123/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 215, in main
    response = requests.get(url)
               ^^^^^^^^^^^^^^^^^
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geralda123/miniconda3/envs/licsbas/lib/python3.12/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='gws-access.jasmin.ac.uk', port=443): Max retries exceeded with url: /public/nceo_geohazards/LiCSAR_products/47/047D_09652_111009/epochs/ (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))

**Comment by yumorishita** [comment]
No idea. Please try again or check your network settings (e.g., proxy).

**Comment by Geralda02** [comment]
Okay, thank you prof

Pada Sab, 10 Mei 2025 18.16, Yu Morishita ***@***.***>
menulis:
