### ISSUE TITLE
Raise ValueError！

### ISSUE THREAD

**Issue by guoluo1999** [yumorishita/LiCSBAS#330]
Reading unw and cc data...
    0/211th unw to identify valid area...
  100/211th unw to identify valid area...
  200/211th unw to identify valid area...
    0/211th cc and unw...
  100/211th cc and unw...
  200/211th cc and unw...

0/211 ifgs are discarded from further processing.
ifg dates        unw_cov coh_av
Traceback (most recent call last):
  File "/home/guoluo/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 356, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/guoluo/LiCSBAS/bin/LiCSBAS11_check_unw.py", line 331, in main
    plot_lib.plot_network(ifgdates, bperp, [], pngfile)
  File "/home/guoluo/LiCSBAS/LiCSBAS_lib/LiCSBAS_plot_lib.py", line 285, in plot_network
    ax.grid(b=True, which='major')
  File "/home/guoluo/miniconda3/envs/licsbas/lib/python3.12/site-packages/matplotlib/axes/_base.py", line 3196, in grid
    self.xaxis.grid(visible, which=which, **kwargs)
  File "/home/guoluo/miniconda3/envs/licsbas/lib/python3.12/site-packages/matplotlib/axis.py", line 1697, in grid
    self.set_tick_params(which='major', **gridkw)
  File "/home/guoluo/miniconda3/envs/licsbas/lib/python3.12/site-packages/matplotlib/axis.py", line 958, in set_tick_params
    kwtrans = self._translate_tick_params(kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guoluo/miniconda3/envs/licsbas/lib/python3.12/site-packages/matplotlib/axis.py", line 1102, in _translate_tick_params
    raise ValueError(
ValueError: keyword grid_b is not recognized; valid keywords are ['size', 'width', 'color', 'tickdir', 'pad', 'labelsize', 'labelcolor', 'labelfontfamily', 'zorder', 'gridOn', 'tick1On', 'tick2On', 'label1On', 'label2On', 'length', 'direction', 'left', 'bottom', 'right', 'top', 'labelleft', 'labelbottom', 'labelright', 'labeltop', 'labelrotation', 'grid_agg_filter', 'grid_alpha', 'grid_animated', 'grid_antialiased', 'grid_clip_box', 'grid_clip_on', 'grid_clip_path', 'grid_color', 'grid_dash_capstyle', 'grid_dash_joinstyle', 'grid_dashes', 'grid_data', 'grid_drawstyle', 'grid_figure', 'grid_fillstyle', 'grid_gapcolor', 'grid_gid', 'grid_in_layout', 'grid_label', 'grid_linestyle', 'grid_linewidth', 'grid_marker', 'grid_markeredgecolor', 'grid_markeredgewidth', 'grid_markerfacecolor', 'grid_markerfacecoloralt', 'grid_markersize', 'grid_markevery', 'grid_mouseover', 'grid_path_effects', 'grid_picker', 'grid_pickradius', 'grid_rasterized', 'grid_sketch_params', 'grid_snap', 'grid_solid_capstyle', 'grid_solid_joinstyle', 'grid_transform', 'grid_url', 'grid_visible', 'grid_xdata', 'grid_ydata', 'grid_zorder', 'grid_aa', 'grid_c', 'grid_ds', 'grid_ls', 'grid_lw', 'grid_mec', 'grid_mew', 'grid_mfc', 'grid_mfcalt', 'grid_ms']

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1498886957
