### ISSUE TITLE
About the use of Step 1-3: Small Baseline Inversion using GPU error

### ISSUE THREAD

**Issue by ghost** [yumorishita/LiCSBAS#338]
Hello, yumorishita.This problem often occurs when I deal with the 13-step use GPU, but it has not appeared in Ubuntu 18.04. The Ubuntu 22.04 I am using now does not know what the problem is?
Process 1078/2691th line (2/5th patch)...
  Reading 271 ifg's unw data...
  547879/1674134 points removed due to not enough ifg data...

  Identifing gaps, and counting n_gap and n_ifg_noloop,
  using GPU...
Traceback (most recent call last):
  File "/home/wangtao/tools/LiCSBAS/bin/LiCSBAS13_sb_inv.py", line 996, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/wangtao/tools/LiCSBAS/bin/LiCSBAS13_sb_inv.py", line 613, in main
    (cp.abs(Aloop_cp[i, :])*(~cp.isnan(unwpatch_cp))).sum(axis=1)
     ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~~~~~
  File "cupy/_core/core.pyx", line 1281, in cupy._core.core._ndarray_base.__mul__
  File "cupy/_core/_kernel.pyx", line 1350, in cupy._core._kernel.ufunc.__call__
  File "cupy/_core/_kernel.pyx", line 645, in cupy._core._kernel._get_out_args_from_optionals
  File "cupy/_core/core.pyx", line 2806, in cupy._core.core._ndarray_init
  File "cupy/_core/core.pyx", line 237, in cupy._core.core._ndarray_base._init_fast
  File "cupy/cuda/memory.pyx", line 738, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1424, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1445, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1116, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1137, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 1382, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
  File "cupy/cuda/memory.pyx", line 1385, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc

**Comment by yumorishita** [comment]
Please upload the full log.
What is the memory size of your GPU?

**Comment by hxwt1987** [comment]
Hello, yumorishita，my graphics card is TUF-RTX3060TI-8GD6X-GAMING, the program has not changed the parameters, and I still use 8000.
[202403161708batch_LiCSBAS_02_16.log](https://github.com/yumorishita/LiCSBAS/files/14623743/202403161708batch_LiCSBAS_02_16.log)

**Comment by yumorishita** [comment]
Please try reducing `p13_mem_size`, e.g., 2000.

https://github.com/yumorishita/LiCSBAS/blob/5db6516a5a9bad31445d916e61e7ee03c3daa1fd/batch_LiCSBAS.sh#L97
