### ISSUE TITLE
 LiCSBAS03op_GACOS.py -i GEOCml1 -o GEOCml1GACOS --fillhole

### ISSUE THREAD

**Issue by sajid-zaman** [yumorishita/LiCSBAS#348]
This step isnt working; can you help out?

(licsbas) sajid@DESKTOP-IB0AUID:/mnt/f/MACD/ascending/071A_05638_131313$ LiCSBAS03op_GACOS.py -i GEOCml1 -o GEOCml1GACOS --fillhole

LiCSBAS03op_GACOS.py ver1.5.5 20201119 Y. Morishita
LiCSBAS03op_GACOS.py -i GEOCml1 -o GEOCml1GACOS --fillhole

Convert ztd/sltd.geo.tif files to sltd.geo files...
  236/236 sltd already exist. Skip

Correct unw data...
  1159/1159 corrected unw already exist. Skip

Traceback (most recent call last):
  File "/home/sajid/MACD/LiCSBAS/bin/LiCSBAS03op_GACOS.py", line 550, in <module>
    sys.exit(main())
  File "/home/sajid/MACD/LiCSBAS/bin/LiCSBAS03op_GACOS.py", line 369, in main
    plot_lib.plot_gacos_info(gacinfofile, pngfile)
  File "/home/sajid/MACD/LiCSBAS/LiCSBAS_lib/LiCSBAS_plot_lib.py", line 149, in plot_gacos_info
    ax1.set_xlim(0, xylim1)
  File "/home/sajid/miniconda3/envs/licsbas/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 3523, in set_xlim
    right = self._validate_converted_limits(right, self.convert_xunits)
  File "/home/sajid/miniconda3/envs/licsbas/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 3439, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf
[LiCSBAS03op_GACOS.py -i GEOCml1 -o GEOCml1GACOS --fillhole.txt](https://github.com/yumorishita/LiCSBAS/files/15089635/LiCSBAS03op_GACOS.py.-i.GEOCml1.-o.GEOCml1GACOS.--fillhole.txt)

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/73#issuecomment-780545132
