### ISSUE TITLE
Permission Error. 

### ISSUE THREAD

**Issue by Indianmedieval** [yumorishita/LiCSBAS#354]
Dear Sir, 

I am getting the Permission Error [Error 1] during the Quality Check code. Even, I have given full permission to access the folder. 

Thank you in advance.

Best Regards

**Comment by yumorishita** [comment]
Please show me the full log.

**Comment by Indianmedieval** [comment]
Please see the full log below:

(my_env) user@osgeolive:/media/sf_Linux_Ak/Landslide/LiCSBAS2-master/LiCSBAS2-master/129A_05935_131313$ LiCSBAS11_check_unw.py -d GEOCml1clip
LiCSBAS11_check_unw.py ver1.3.3 20210402 Y. Morishita
LiCSBAS11_check_unw.py -d GEOCml1clip

coh_thre     : 0.05
unw_cov_thre : 0.3

Size         : 15 x 11

Reading unw and cc data...
    0/3338th unw to identify valid area...
  100/3338th unw to identify valid area...
  200/3338th unw to identify valid area...
  300/3338th unw to identify valid area...
  400/3338th unw to identify valid area...
  500/3338th unw to identify valid area...
  600/3338th unw to identify valid area...
  700/3338th unw to identify valid area...
  800/3338th unw to identify valid area...
  900/3338th unw to identify valid area...
  1000/3338th unw to identify valid area...
  1100/3338th unw to identify valid area...
  1200/3338th unw to identify valid area...
  1300/3338th unw to identify valid area...
  1400/3338th unw to identify valid area...
  1500/3338th unw to identify valid area...
  1600/3338th unw to identify valid area...
  1700/3338th unw to identify valid area...
  1800/3338th unw to identify valid area...
  1900/3338th unw to identify valid area...
  2000/3338th unw to identify valid area...
  2100/3338th unw to identify valid area...
  2200/3338th unw to identify valid area...
  2300/3338th unw to identify valid area...
  2400/3338th unw to identify valid area...
  2500/3338th unw to identify valid area...
  2600/3338th unw to identify valid area...
  2700/3338th unw to identify valid area...
  2800/3338th unw to identify valid area...
  2900/3338th unw to identify valid area...
  3000/3338th unw to identify valid area...
  3100/3338th unw to identify valid area...
  3200/3338th unw to identify valid area...
  3300/3338th unw to identify valid area...
    0/3338th cc and unw...
  100/3338th cc and unw...
  200/3338th cc and unw...
  300/3338th cc and unw...
  400/3338th cc and unw...
/media/sf_Linux_Ak/Landslide/LiCSBAS2-master/LiCSBAS2-master/bin/LiCSBAS11_check_unw.py:232: RuntimeWarning: Mean of empty slice
  coh_avg_ifg.append(np.nanmean(coh[bool_valid])) # Use valid area only
  500/3338th cc and unw...
  600/3338th cc and unw...
  700/3338th cc and unw...
  800/3338th cc and unw...
  900/3338th cc and unw...
  1000/3338th cc and unw...
  1100/3338th cc and unw...
  1200/3338th cc and unw...
  1300/3338th cc and unw...
  1400/3338th cc and unw...
  1500/3338th cc and unw...
  1600/3338th cc and unw...
  1700/3338th cc and unw...
  1800/3338th cc and unw...
  1900/3338th cc and unw...
  2000/3338th cc and unw...
  2100/3338th cc and unw...
  2200/3338th cc and unw...
  2300/3338th cc and unw...
  2400/3338th cc and unw...
  2500/3338th cc and unw...
  2600/3338th cc and unw...
  2700/3338th cc and unw...
  2800/3338th cc and unw...
  2900/3338th cc and unw...
  3000/3338th cc and unw...
  3100/3338th cc and unw...
  3200/3338th cc and unw...
  3300/3338th cc and unw...
Traceback (most recent call last):
  File "/media/sf_Linux_Ak/Landslide/LiCSBAS2-master/LiCSBAS2-master/bin/LiCSBAS11_check_unw.py", line 356, in <module>
    sys.exit(main())
  File "/media/sf_Linux_Ak/Landslide/LiCSBAS2-master/LiCSBAS2-master/bin/LiCSBAS11_check_unw.py", line 283, in main
    os.symlink(os.path.relpath(rasorg, bad_ifg_rasdir), os.path.join(bad_ifg_rasdir, rasname))
PermissionError: [Errno 1] Operation not permitted: '../../GEOCml1clip/20150611_20190602/20150611_20190602.unw.png' -> '/media/sf_Linux_Ak/Landslide/LiCSBAS2-master/LiCSBAS2-master/129A_05935_131313/TS_GEOCml1clip/11bad_ifg_ras/20150611_20190602.unw.png'

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2102667929

**Comment by Indianmedieval** [comment]
Dear Sir, 

I using the sharing folder inside the system but in drive D instead of C due to space issue

I have tried #89 but I am still receiving the same error.

what do you mean by the format of disk exactly.

Best,

**Comment by Indianmedieval** [comment]
#89 as I mentioned I did this:

(my_env) user@osgeolive:/media/sf_Linux_Ak/Landslide/LiCSBAS2-master/LiCSBAS2-master$ chmod -R 777 129A_05935_131313
(my_env) user@osgeolive:/media/sf_Linux_Ak/Landslide/LiCSBAS2-master/LiCSBAS2-master$ source bashrc_LiCSBAS.sh
(my_env) user@osgeolive:/media/sf_Linux_Ak/Landslide/LiCSBAS2-master/LiCSBAS2-master$ cd 129A_05935_131313
(my_env) user@osgeolive:/media/sf_Linux_Ak/Landslide/LiCSBAS2-master/LiCSBAS2-master/129A_05935_131313$ LiCSBAS11_check_unw.py -d GEOCml1clip

LiCSBAS11_check_unw.py ver1.3.3 20210402 Y. Morishita
LiCSBAS11_check_unw.py -d GEOCml1clip

coh_thre     : 0.05
unw_cov_thre : 0.3

Size         : 15 x 11

Reading unw and cc data...
    0/3338th unw to identify valid area...
  100/3338th unw to identify valid area...
  200/3338th unw to identify valid area...
  300/3338th unw to identify valid area...
  400/3338th unw to identify valid area...
  500/3338th unw to identify valid area...
  600/3338th unw to identify valid area...
  700/3338th unw to identify valid area...
  800/3338th unw to identify valid area...
  900/3338th unw to identify valid area...
  1000/3338th unw to identify valid area...
  1100/3338th unw to identify valid area...
  1200/3338th unw to identify valid area...
  1300/3338th unw to identify valid area...
  1400/3338th unw to identify valid area...
  1500/3338th unw to identify valid area...
  1600/3338th unw to identify valid area...
  1700/3338th unw to identify valid area...
  1800/3338th unw to identify valid area...
  1900/3338th unw to identify valid area...
  2000/3338th unw to identify valid area...
  2100/3338th unw to identify valid area...
  2200/3338th unw to identify valid area...
  2300/3338th unw to identify valid area...
  2400/3338th unw to identify valid area...
  2500/3338th unw to identify valid area...
  2600/3338th unw to identify valid area...
  2700/3338th unw to identify valid area...
  2800/3338th unw to identify valid area...
  2900/3338th unw to identify valid area...
  3000/3338th unw to identify valid area...
  3100/3338th unw to identify valid area...
  3200/3338th unw to identify valid area...
  3300/3338th unw to identify valid area...
    0/3338th cc and unw...
  100/3338th cc and unw...
  200/3338th cc and unw...
  300/3338th cc and unw...
  400/3338th cc and unw...
/media/sf_Linux_Ak/Landslide/LiCSBAS2-master/LiCSBAS2-master/bin/LiCSBAS11_check_unw.py:232: RuntimeWarning: Mean of empty slice
  coh_avg_ifg.append(np.nanmean(coh[bool_valid])) # Use valid area only
  500/3338th cc and unw...
  600/3338th cc and unw...
  700/3338th cc and unw...
  800/3338th cc and unw...
  900/3338th cc and unw...
  1000/3338th cc and unw...
  1100/3338th cc and unw...
  1200/3338th cc and unw...
  1300/3338th cc and unw...
  1400/3338th cc and unw...
  1500/3338th cc and unw...
  1600/3338th cc and unw...
  1700/3338th cc and unw...
  1800/3338th cc and unw...
  1900/3338th cc and unw...
  2000/3338th cc and unw...
  2100/3338th cc and unw...
  2200/3338th cc and unw...
  2300/3338th cc and unw...
  2400/3338th cc and unw...
  2500/3338th cc and unw...
  2600/3338th cc and unw...
  2700/3338th cc and unw...
  2800/3338th cc and unw...
  2900/3338th cc and unw...
  3000/3338th cc and unw...
  3100/3338th cc and unw...
  3200/3338th cc and unw...
  3300/3338th cc and unw...
Traceback (most recent call last):
  File "/media/sf_Linux_Ak/Landslide/LiCSBAS2-master/LiCSBAS2-master/bin/LiCSBAS11_check_unw.py", line 356, in <module>
    sys.exit(main())
  File "/media/sf_Linux_Ak/Landslide/LiCSBAS2-master/LiCSBAS2-master/bin/LiCSBAS11_check_unw.py", line 283, in main
    os.symlink(os.path.relpath(rasorg, bad_ifg_rasdir), os.path.join(bad_ifg_rasdir, rasname))
PermissionError: [Errno 1] Operation not permitted: '../../GEOCml1clip/20150611_20190602/20150611_20190602.unw.png' -> '/media/sf_Linux_Ak/Landslide/LiCSBAS2-master/LiCSBAS2-master/129A_05935_131313/TS_GEOCml1clip/11bad_ifg_ras/20150611_20190602.unw.png'
