### ISSUE TITLE
Unable to open object (object 'mask' doesn't exist)

### ISSUE THREAD

**Issue by mirzawaqar** [yumorishita/LiCSBAS#361]
While displaying the time series of the displacement and velocity I am getting the following error. Kindly guide how to fix it. 

user@user31:/media/hdd3/RD003_Land_Deformation_Mapping/Pakistan/Lahore/SBAS$ LiCSBAS_plot_ts.py -i TS_GEOCml1_GACOS_masked_clip/cum.h5 &
[1] 821042
contec@contec31:/media/hdd3/RD003_Land_Deformation_Mapping/Pakistan/Lahore/SBAS$ 
LiCSBAS_plot_ts.py ver1.14.0 20230219 Y. Morishita
LiCSBAS_plot_ts.py -i TS_GEOCml1_GACOS_masked_clip/cum.h5

Reading TS_GEOCml1_GACOS_masked_clip/cum.h5
Reading mask
Traceback (most recent call last):
  **File "/home/contec/Softwares/LiCSBAS2/bin/LiCSBAS_plot_ts.py", line 408, in <module>
    mask_vel = cumh5['mask'][()]
               ~~~~~^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/contec/Softwares/anaconda3/envs/licsbas/lib/python3.12/site-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 241, in h5py.h5o.open
KeyError: "Unable to open object (object 'mask' doesn't exist)"**

**Comment by yumorishita** [comment]
I am not sure but maybe the cum.h5 is corrupted or incomplete.

**Comment by mirzawaqar** [comment]
Got it. I re-run and the problem was resolved.
