### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by ajisugiantoro123** [yumorishita/LiCSBAS#366]
Hello Prof, I found this error when processing from step 01.

Start step: 01
End step:   16
Log file:   log/202406051204batch_LiCSBAS_01_16.log

LiCSBAS01_get_geotiff.py ver1.6.4 20230215 Y. Morishita
LiCSBAS01_get_geotiff.py -f 142A_09168_080913 -s 20221101 -e 20230930

Frame ID is 142A_09168_080913

142A_09168_080913.geo.E.tif already exist. Skip download.
142A_09168_080913.geo.N.tif already exist. Skip download.
142A_09168_080913.geo.U.tif already exist. Skip download.
142A_09168_080913.geo.hgt.tif already exist. Skip download.

Download baselines
    baselines, 5.59KB, 1s, 5.59KB/s
Download network.png
    network.png, 757.75KB, 2s, 378.87KB/s
Download metadata.txt
    metadata.txt, 254.0B, 1s, 254.0B/s

142A_09168_080913.geo.mli.tif already exist. Skip.

Download geotiff of unw and cc
Traceback (most recent call last):
  File "/mnt/HDD_8TB/skripsi20/aji/palu23/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 500, in <module>
    sys.exit(main())
  File "/mnt/HDD_8TB/skripsi20/aji/palu23/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 322, in main
    response = requests.get(url_ifgdir)
  File "/home/geodinamika/miniconda3/envs/aji20/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/geodinamika/miniconda3/envs/aji20/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/geodinamika/miniconda3/envs/aji20/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/geodinamika/miniconda3/envs/aji20/lib/python3.10/site-packages/requests/sessions.py", line 724, in send
    history = [resp for resp in gen]
  File "/home/geodinamika/miniconda3/envs/aji20/lib/python3.10/site-packages/requests/sessions.py", line 724, in <listcomp>
    history = [resp for resp in gen]
  File "/home/geodinamika/miniconda3/envs/aji20/lib/python3.10/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

Can you help me, Prof? Thank you

**Comment by EllenLee183** [comment]
I also encountered the same problem

**Comment by MIEMESSI** [comment]
Dear Professor, I have encountered this problem, can you help me
![image](https://github.com/yumorishita/LiCSBAS/assets/161692921/9718cb6f-9047-456f-8b8d-8e92309d521d)

**Comment by yumorishita** [comment]
The bug was fixed in LiCSBAS2 (https://github.com/yumorishita/LiCSBAS2/pull/55). Please use LiCSBAS2 or apply the fix in your local LiCSBAS script.

**Comment by erlangga0909** [comment]
Hi Morishita,

I'm having some trouble with downloading Tiff files on frame 039A_09827_040302. I've tried to use LiCSBAS and LiCSBAS2, but I'm stuck on the download issue
![Check](https://github.com/yumorishita/LiCSBAS/assets/94942877/c1235f78-8e55-4145-9761-cb8e63b17ff3)

Could you please help me understand how to fix it?
Thank you so much for considering my request.

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/370#issuecomment-2184930345
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2173156010
