### ISSUE TITLE
traceback error while searching latest epoch

### ISSUE THREAD

**Issue by maulanaheno** [yumorishita/LiCSBAS#368]
Searching latest epoch for mli...
Traceback (most recent call last):
  File "/home/maulanaheno/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 500, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/maulanaheno/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 213, in main
    response = requests.get(url)
               ^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

what is this error means?

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/367#issuecomment-2152466246
