### ISSUE TITLE
latest epoch for mli

### ISSUE THREAD

**Issue by kashkoulimohammad** [yumorishita/LiCSBAS#372]
Hi all,
When I edited the batch_LiCSBAS.sh for my interest and run it, I faced with this error:
`Searching latest epoch for mli...
Traceback (most recent call last):
  File "/root/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 499, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 212, in main
    response = requests.get(url)
               ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/licsbas/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/licsbas/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/licsbas/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/licsbas/lib/python3.12/site-packages/requests/sessions.py", line 724, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/licsbas/lib/python3.12/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.`
How can I fix it?

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2156004788

**Comment by kashkoulimohammad** [comment]
Thank you @yumorishita.
It solved.
