### ISSUE TITLE
checking existing unw error

### ISSUE THREAD

**Issue by maulanaheno** [yumorishita/LiCSBAS#375]
Download geotiff of unw and cc
1119 IFGs available from 20180102 to 20230406
Checking existing unw and cc (4 parallel, may take time)...
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 456, in check_exist_wrapper
    rc = tools_lib.comp_size_time(url_data, path_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/LiCSBAS2/LiCSBAS_lib/LiCSBAS_tools_lib.py", line 78, in comp_size_time
    response = requests.head(file_remote, allow_redirects=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/requests/api.py", line 100, in head
    return request("head", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/maulanaheno/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 500, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/maulanaheno/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 352, in main
    rc = p.map(check_exist_wrapper, args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maulanaheno/miniconda3/envs/licsbas2/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

what is this error mean?? and how do i fix it?

**Comment by yumorishita** [comment]
Probably https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2156004788
