### ISSUE TITLE
LiCSBAS12_loop_closure.py

### ISSUE THREAD

**Issue by oguzhannysr** [yumorishita/LiCSBAS#399]
Hello @yumorishita,  the computer gets stuck at this step. What is the reason for this? I do it without cropping the area.
![image](https://github.com/user-attachments/assets/ced9e050-8863-44ab-b249-ee41aedfbe5f)
[202409050828batch_LiCSBAS_01_16.log](https://github.com/user-attachments/files/16885326/202409050828batch_LiCSBAS_01_16.log)

**Comment by yumorishita** [comment]
Try n_para=1.
https://github.com/yumorishita/LiCSBAS/blob/5db6516a5a9bad31445d916e61e7ee03c3daa1fd/batch_LiCSBAS.sh#L24

**Comment by oguzhannysr** [comment]
@yumorishita , I try by setting n12_para to 1

**Comment by oguzhannysr** [comment]
@yumorishita , Now I'm stuck here, which n_para should I change?


```
  Running  64000/ 65117th point...
  Running  63000/ 65117th point...
  Running  61000/ 65117th point...
  Running  62000/ 65117th point...
  Running  65000/ 65117th point...
  Running  60000/ 65117th poi
```nt...
  Elapsed time for 11th patch: 00h 05m 58s

Process 624/2689th line (12/52th patch)...
  Reading 724 ifg's unw data...
  84278/183768 points removed due to not enough ifg data...

  Identifing gaps, and counting n_gap and n_ifg_noloop,
  with 16 parallel processing...
    Running  1/16th patch...
    Running  2/16th patch...
    Running  3/16th patch...
    Running  4/16th patch...
    Running  5/16th patch...
    Running  6/16th patch...
    Running  9/16th patch...
    Running 10/16th patch...
    Running 11/16th patch...
    Running 12/16th patch...
    Running 14/16th patch...
    Running 15/16th patch...
    Running 16/16th patch...
    Running  8/16th patch...
    Running  7/16th patch...
    Running 13/16th patch...

**Comment by yumorishita** [comment]
I already mentioned above.

**Comment by oguzhannysr** [comment]
@yumorishita, 
```
Process 2673/2689th line (243/251th patch)...
  Reading 724 ifg's unw data...
  38874/38874 points removed due to not enough ifg data...
  Elapsed time for 243th patch: 00h 05m 04s

Process 2684/2689th line (244/251th patch)...
  Reading 724 ifg's unw data...
  38874/38874 points removed due to not enough ifg data...
  Elapsed time for 244th patch: 00h 00m 57s

Process 2695/2689th line (245/251th patch)...
  Reading 724 ifg's unw data...
Traceback (most recent call last):
  File "/home/yasar/LICSBAS/bin/LiCSBAS13_sb_inv.py", line 996, in <module>
    sys.exit(main())
  File "/home/yasar/LICSBAS/bin/LiCSBAS13_sb_inv.py", line 541, in main
    unw = np.fromfile(f, dtype=np.float32, count=countl).reshape((lengththis, width))*coef_r2m
ValueError: cannot reshape array of size 17670 into shape (11,3534)
```

**Comment by yumorishita** [comment]
Maybe some of the GEOCml1/*/*unw files are corrupted. Please check all the files have the same size.

**Comment by oguzhannysr** [comment]
@yumorishita , There are more than 1000 folders, how can I do this more easily? Also, if there is a corrupt file, what should I do? Should I go back to the beginning?

**Comment by yumorishita** [comment]
Remove corrupted files and restart from step11.

**Comment by oguzhannysr** [comment]
@yumorishita , I checked for corrupt files, but all files were the same size and as they should be. I don't know what to do now?

**Comment by oguzhannysr** [comment]
thank you...

**Comment by as1234554321** [comment]
haii @oguzhannysr 
hello, how do I get this much decompose?, I only got 1 UD file
can you help me to tells how to process decomposition appropriately and slowly. Thank You

**Comment by yumorishita** [comment]
> How technically correct is it to separate each image pair as east-west and up-down using the cumulative los data produced for the ascending and descending orbits as of 2016?

What do you mean by "as of 2016"?

**Comment by yumorishita** [comment]
How did you treat the date difference between ascending and descending in the decomposition?

**Comment by oguzhannysr** [comment]
@yumorishita , as it can be seen in the image, after the date 20211218, the dates of the couples start not to match with each other. Therefore, I made ud-ew separation based on two pairs in 6-day periods. For example, I matched the date 20211224 in the ascending orbit with the date 20211230 in the descending orbit and made the separation as ud-ew. How technically correct is this? Does it provide me with the correct trend of the deformation? 


![image](https://github.com/user-attachments/assets/6802b145-cfd7-41df-b8de-426c834506bf)

**Comment by yumorishita** [comment]
If the deformation is slow and we can ignore the 6 day difference, I think your approach makes sense.

**Comment by oguzhannysr** [comment]
@yumorishita , Thank you sir, but is the reason why the data dates do not match after a certain time (after 2021) due to the failure of the Sentinel-1 satellite or due to incomplete processing of data in the COMET system?

**Comment by yumorishita** [comment]
I don't know. You should check it yourself by searching for data, e.g., on ASF.

**Comment by oguzhannysr** [comment]
dear @yumorishita , Is there an anomaly in n_loop_err in my results here? Do you think I should set p15_n_loop_err_thre=0 and run it again?

```
Noise index    : Threshold  (rate to be masked)
- coh_avg      : 0.05       ( 0.0%)
- n_unw        :  531       ( 0.0%)
- vstd         :  100 mm/yr ( 0.0%)
- maxTlen      :    1 yr    ( 0.0%)
- n_gap        :   10       ( 0.0%)
- stc          :    5 mm    ( 0.0%)
- n_ifg_noloop :   50       ( 0.5%)
- n_loop_err   :    5       (20.2%)
- resid_rms    :    2 mm    ( 2.5%)

Masked pixels  : 224/1109 (20.2%)
Kept pixels    : 885/1109 (79.8%)
```

**Comment by yumorishita** [comment]
The result looks normal.

**Comment by oguzhannysr** [comment]
@yumorishita , I got an error like the following. I couldn't understand why. My other files are below. What do you think is the reason?

[202409190909batch_LiCSBAS_01_16.log](https://github.com/user-attachments/files/17054769/202409190909batch_LiCSBAS_01_16.log)
[batch_LiCSBAS.txt](https://github.com/user-attachments/files/17054786/batch_LiCSBAS.txt)


```
Create unw and cc
  1 parallel processing...
    0/1258th IFG...
/home/yasar/LICSBAS/bin/LiCSBAS02_ml_prep.py:441: RuntimeWarning: invalid value encountered in cast
  cc = cc.astype(np.uint8) ##nan->0, max255, auto-floored
/home/yasar/LICSBAS/bin/LiCSBAS02_ml_prep.py:441: RuntimeWarning: invalid value encountered in cast
  cc = cc.astype(np.uint8) ##nan->0, max255, auto-floored
/home/yasar/LICSBAS/bin/LiCSBAS02_ml_prep.py:441: RuntimeWarning: invalid value encountered in cast
  cc = cc.astype(np.uint8) ##nan->0, max255, auto-floored
```

**Comment by as1234554321** [comment]
@yumorishita 
I got some error, please help me, thankyou 
1) the mask pixel percentage is very high is that normal? 
![image](https://github.com/user-attachments/assets/5cefbc1c-c1a2-4a37-940e-465f58c60df3)
2)lots of ifg nan Does it have to be deleted manually or is it deleted automatically? 
![image](https://github.com/user-attachments/assets/d76697b7-bd37-4469-acca-549af61a1e3c)
3)What does this image mean and what does it affect?
![image](https://github.com/user-attachments/assets/1ead384c-c592-4273-a661-b650b2c5f177)
/home/winda2/miniconda3/envs/licsbas/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1879: RuntimeWarning: Degrees of freedom <= 0 for slice. var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

**Comment by yumorishita** [comment]
@oguzhannysr I am not sure but cc files may be corrupted. Please check the contents.

**Comment by yumorishita** [comment]
@as1234554321 
1. It can be normal
2. automatically deleted
3. I have no idea without the full log

**Comment by as1234554321** [comment]
this full log
[202409191148batch_LiCSBAS_01_16.log](https://github.com/user-attachments/files/17058865/202409191148batch_LiCSBAS_01_16.log)

**Comment by yumorishita** [comment]
These messages are just warnings, not errors, and can be ignored. The processing was successfully finished with no error.

**Comment by oguzhannysr** [comment]
> @yumorishita , Now I'm stuck here, which n_para should I change?
> 
> ```
>   Running  64000/ 65117th point...
>   Running  63000/ 65117th point...
>   Running  61000/ 65117th point...
>   Running  62000/ 65117th point...
>   Running  65000/ 65117th point...
>   Running  60000/ 65117th poi
> ```nt...
>   Elapsed time for 11th patch: 00h 05m 58s
> 
> Process 624/2689th line (12/52th patch)...
>   Reading 724 ifg's unw data...
>   84278/183768 points removed due to not enough ifg data...
> 
>   Identifing gaps, and counting n_gap and n_ifg_noloop,
>   with 16 parallel processing...
>     Running  1/16th patch...
>     Running  2/16th patch...
>     Running  3/16th patch...
>     Running  4/16th patch...
>     Running  5/16th patch...
>     Running  6/16th patch...
>     Running  9/16th patch...
>     Running 10/16th patch...
>     Running 11/16th patch...
>     Running 12/16th patch...
>     Running 14/16th patch...
>     Running 15/16th patch...
>     Running 16/16th patch...
>     Running  8/16th patch...
>     Running  7/16th patch...
>     Running 13/16th patch...
> ```

@yumorishita ,Hello sir, the problem still persists. I want to process the entire tile at once, but I stay in the same step. I can't understand whether my computer's RAM is not enough.

**Comment by as1234554321** [comment]
thankyou sir, 
Hi sir,  I want ask again @yumorishita 
the results of licsbas processing in the area of interest showed a LOS value (+)  is uplift while gmtsar processing a LOS (-) is subsidence and supported by paper in the area also subsidence. Both processing (licsbas and gmtsar) use the same time period
1) what causes the anomaly in the results in licsbas processing ? 
2) what affects these results?

**Comment by yumorishita** [comment]
@oguzhannysr What is your RAM size?

**Comment by yumorishita** [comment]
@as1234554321 I have no idea from this limited information.

**Comment by oguzhannysr** [comment]
> @oguzhannysrRAM boyutunuz nedir?

16 GB

**Comment by oguzhannysr** [comment]
> @oguzhannysrRAM boyutunuz nedir?

@yumorishita , 16 gb

**Comment by as1234554321** [comment]
> @as1234554321 I have no idea from this limited information.

I have processed the land subsidence using licsbas batch by changing the "y" parameter in the gacos, mask and clip steps, others are default.  However, the results are very different from the journal which states that all of these areas experienced land subsidence, while the results of Licsbas in the southern part experienced uplift. Below I attach the difference between the journal and the LICSBAS results. 
What causes this anomaly? and if it is due to licsbas processing, which part should be changed?
 Thank You
![gabung](https://github.com/user-attachments/assets/ae7d3338-6a39-4aae-8d6f-a1055cf51717)

**Comment by as1234554321** [comment]
sorry sir, I ask different question
I have stuck proses in this step, What should I do?
![image](https://github.com/user-attachments/assets/e87b5fb6-bb5a-48d1-b2e0-108d00435f98)

**Comment by yumorishita** [comment]
@oguzhannysr 16GB should be generally enough. Is your environment WSL? Which OS do you use?

**Comment by yumorishita** [comment]
@as1234554321 I think LiCSBAS also shows subsidence and they are consistent.
Regarding stuck, see https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1500877478.

**Comment by as1234554321** [comment]
> @as1234554321Saya pikir LiCSBAS juga menunjukkan penurunan dan hasilnya konsisten. Mengenai macet, lihat [#244 (komentar)](https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-1500877478) .

but in south area uplift, I think should subsidence but the result uplift.what cause this different?

**Comment by oguzhannysr** [comment]
> @oguzhannysr 16GB should be generally enough. Is your environment WSL? Which OS do you use?

@yumorishita, Yes, I run LICSBAS in WSL in Windows.

**Comment by yumorishita** [comment]
@as1234554321 Now I see your point. You should set the reference point in the south area.

**Comment by yumorishita** [comment]
@oguzhannysr I have never used WSL but it seems that the stuck tends to happen in WSL according to the reported issues. I suggest using the VirtualBox as I do.

**Comment by as1234554321** [comment]
> @as1234554321Sekarang saya mengerti maksud Anda. Anda harus menetapkan titik referensi di area selatan.

based on your comment in another issue, if I have clipped (step 0-5) there is no need to set the ref area because licsbas automatically determines a stable point. but now you suggest changing it. I am confused. 
If I equate the ref area using licsbas cum2vel with the long/lat point at the time of clip (step 0-5) is there a possibility that the southern velocity area will change (-)? or the ref point/ref area must be different from step 0-5?

**Comment by as1234554321** [comment]
hi sir @yumorishita 
i was set reference point with -- licsbas cum2vel --ref.geo but the result same.  the velocity of the south area remains positive/uplift. 
pic 1 ( process licsbas cum2vel done)
![image](https://github.com/user-attachments/assets/c13cdf12-bd2c-461e-9c8a-f6ff15f66f2c)
pic 2 the plot LiCSBAS_plot_ts.py of the result licsbascum2 vel. left is ascending and right is desending. both of them in south area, velocity value still positif, but in other journal/paper this area was landsubsidence. what causes this difference?
![image](https://github.com/user-attachments/assets/92a865e6-8207-42f6-9189-7fd7769a29e9)

**Comment by yumorishita** [comment]
step05 does not set any reference point but just clips the area.
The auto-determined reference is selected using the median under the assumption that more than half of the pixels are stable. In your case, this assumption does not hold and the stable area falsely has uplift.
The option `--ref_geo 110.22/110/59/-7.19/-6.90` specifies the entire area, not the southern area. You must specify the small area in the stable southern area, e.g., `-r 200:210/150:160`.

**Comment by as1234554321** [comment]
Ohh I see, thankyou for your answer and suggestion
1.ref point stable means an area where there is no uplift/land subsidence, is that right/wrong?
2.how to determine a stable ref point?

**Comment by yumorishita** [comment]
1. Right.
2. It needs external information or can be arbitrary.
3. You should also set `-r` option for LiCSBAS_plot_ts.py
4. I guess there was no valid point in the selected reference area. You should change the reference area.

**Comment by yumorishita** [comment]
The pixel corresponding to the GPS CORS can be a ref point if it exists.
Please read the usage of LiCSBAS_plot_ts.py.
Your case is the good example if you change the ref point.

**Comment by as1234554321** [comment]
thankyou sir, I will try it
permission to make sure sir, so I changed the reference point using licsbascum2vel.py then run on licsbasplot.py + licsbascum2vel result + -r GPS CORS point. is that right?

**Comment by yumorishita** [comment]
licsbascum2vel.py does not affect licsbasplot.py at all because the output of licsbascum2vel.py is not used in licsbasplot.py.
You can use --ref_geo option instead of -r. Please read the usage.

**Comment by as1234554321** [comment]
> licsbascum2vel.py sama sekali tidak memengaruhi licsbasplot.py karena output licsbascum2vel.py tidak digunakan dalam licsbasplot.py. Anda dapat menggunakan opsi --ref_geo sebagai ganti -r. Harap baca penggunaannya.

so what tools do i use to change the ref point and how do i know if the velocity has changed?
sorry I don't know how to do it, thankyou

**Comment by yumorishita** [comment]
You should specify the reference for each command.

**Comment by as1234554321** [comment]
> Anda harus menentukan referensi untuk setiap perintah.

yes I know I have to change the ref on every command. but I'm confused about is what commands should be used? Can you provide step by step tools that should be used. I've read the issue related to the ref area but I still miss understanding.
thankyou
#102 #131

**Comment by yumorishita** [comment]
It depends on what output you want. Please carefully read the usage for each command. All the required information is there.

**Comment by as1234554321** [comment]
> Tergantung pada keluaran yang Anda inginkan. Harap baca dengan saksama penggunaan untuk setiap perintah. Semua informasi yang diperlukan tersedia di sana.

I want to get the value of the velocity file which has changed the ref point and then used it to decompose. So what tools should I use? thank you

**Comment by yumorishita** [comment]
How about -r 190:200/100:110?

**Comment by as1234554321** [comment]
> Bagaimana dengan -r 190:200/100:110?

thankyou sir, I will try it, How do I use the GPS lat/lot cors point (-6.9872, 110.3769) for to be used a reference (pixel)?
because it's just a point not an area so I can't use --ref geo (long/long/lat/lat).

**Comment by yumorishita** [comment]
For example, `--ref_geo 110.376/110.377/-6.987/-6.988`.

**Comment by as1234554321** [comment]
> For example, `--ref_geo 110.376/110.377/-6.987/-6.988`.
I tried to do it but the result was an error
![image](https://github.com/user-attachments/assets/cc2fb382-f54e-4adc-ae96-8350399066ac)

**Comment by as1234554321** [comment]
Hi sir, I want to ask you again about this, 
gambar kiri (hasil licsbas) gambar kanan (STAMPS)
![image](https://github.com/user-attachments/assets/18d7c209-79ed-4c55-8d58-fb293a038adc)
I have changed the CORS ref point so the brown color (Licsbas) showing the LOS value is uplift while the blue color (STAMPS) shows no deformation (stable). How could this be different?
what causes this?
can you help solve the problem.  
Is there a provision that the area can be said to be stable (even if it experiences small uplift/subsidence)?

**Comment by yumorishita** [comment]
I cannot see a significant difference between them.

**Comment by as1234554321** [comment]
licsbas result range uplift 0-30 mm but STA MPS just 0 (stable) 
Is there a provision for the area to be said to be stable even if there is a small uplift/subsidence?

**Comment by yumorishita** [comment]
If you set the reference there, the displacement will become 0.

**Comment by yumorishita** [comment]
Change the value for --ref_geo option.

**Comment by as1234554321** [comment]
> Change the value for --ref_geo option.

sorry i dont understand about this, can you give an example please?

**Comment by as1234554321** [comment]
Hi sir, I was change referensi area but the result as same just different in value. 
there is no significant difference. The brown area remains uplifted while the STAMPS, gmtsar, ps insar processing results show subsidence. Can you help me to resolve this?

**Comment by as1234554321** [comment]
> Jika Anda menetapkan referensi di sana, perpindahan akan menjadi 0.
sorry I follow up about this
Halo Pak, saya telah mengubah area referensi tetapi hasilnya sama saja, hanya berbeda nilainya.
Tidak ada perbedaan yang signifikan. Area berwarna cokelat tetap terangkat sementara hasil pemrosesan STAMPS, gmtsar, ps insar menunjukkan penurunan. Dapatkah Anda membantu saya menyelesaikan ini?

**Comment by yumorishita** [comment]
I see. Use `--nomask` option.

**Comment by as1234554321** [comment]
> > Jika Anda menetapkan referensi di sana, perpindahan akan menjadi 0.
> 
> sorry I follow up about this, I process this using a batch script with default parameter >change ref area with cum2vel> decompose Hello Sir, I have changed the reference area but the result is the same, only the values ​​are different. There is no significant difference. The brown area remains uplift while the STAMPS, gmtsar, ps insar processing results show subsidence. Can you help me solve this issue?

how about this sir?

**Comment by yumorishita** [comment]
I cannot understand your situation.

**Comment by yumorishita** [comment]
Let me close this ticket because there seem to be no more questions.
