### ISSUE TITLE
cannot reshape array of size 5420 error when using LiCSBAS_flt2geotiff to convert vel.mskd file to geotiff

### ISSUE THREAD

**Issue by faraksoch1881** [yumorishita/LiCSBAS#404]
Dear Dr. Yumorishita,
I'm trying  convert the vel.mskd or vel.filt.mskd using LiCSBAS_flt2geotiff.py but i'm getting error "cannot reshape array of size 5420 into shape (2714,2944). Here is my input and errors.
```
(base) sagar@sagar-Precision-5820-Tower:~/sdb/licsbas/019D_06217_131313$ LiCSBAS_flt2geotiff.py -i TS_GEOCml1GACOSclip/results/vel.mskd -p GEOCml1/EQA.dem_par

LiCSBAS_flt2geotiff.py ver1.5.1 20210209 Y. Morishita
LiCSBAS_flt2geotiff.py -i TS_GEOCml1GACOSclip/results/vel.mskd -p GEOCml1/EQA.dem_par
Use gdal module
Traceback (most recent call last):
  File "/home/sagar/Downloads/LiCSBAS2-master/bin/LiCSBAS_flt2geotiff.py", line 213, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/sagar/Downloads/LiCSBAS2-master/bin/LiCSBAS_flt2geotiff.py", line 190, in main
    data = io_lib.read_img(infile, length, width, endian=endian)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sagar/Downloads/LiCSBAS2-master/LiCSBAS_lib/LiCSBAS_io_lib.py", line 199, in read_img
    data = np.fromfile(file, dtype=dtype).reshape((length, width))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 54250 into shape (2714,2944)
```

how to solve this ? am i doing somethign wrong? Also i used LiCSBAS_cum2vel.py to create a vel.mskd file and use that but received same error

<img width="440" alt="Screenshot 2024-09-15 223428" src="https://github.com/user-attachments/assets/7ed2491c-654a-4ef9-949d-4250f6185f90">

**Comment by faraksoch1881** [comment]
I figure this out myself. For anyone who might get same error. Here is solution

https://github.com/yumorishita/LiCSBAS/issues/115#issuecomment-876054311
