### ISSUE TITLE
Getting an error to download unwrapped interferogram and coherence files for a frame id

### ISSUE THREAD

**Issue by pratanu9083** [yumorishita/LiCSBAS#405]
Code I am using : LiCSBAS01_get_geotiff.py -s 20200101 -e 20240624

Result: LiCSBAS01_get_geotiff.py ver1.6.3 20201207 Y. Morishita
LiCSBAS01_get_geotiff.py -s 20200101 -e 20240624

Frame ID is 048D_06252_131313

Download 048D_06252_131313.geo.E.tif
    048D_06252_131313.geo.E.tif, 22.92MB, 3s, 7.64MB/s
Download 048D_06252_131313.geo.N.tif
    048D_06252_131313.geo.N.tif, 22.92MB, 3s, 7.64MB/s
Download 048D_06252_131313.geo.U.tif
    048D_06252_131313.geo.U.tif, 22.92MB, 3s, 7.64MB/s
Download 048D_06252_131313.geo.hgt.tif
    048D_06252_131313.geo.hgt.tif, 23.14MB, 3s, 7.71MB/s

Download baselines
    baselines, 8.33KB, 1s, 8.33KB/s
Download network.png
    network.png, 470.77KB, 1s, 470.77KB/s
Download metadata.txt
    metadata.txt, 247.0B, 1s, 247.0B/s

Searching latest epoch for mli...
Traceback (most recent call last):
  File "/home/sar-rnd/anaconda3/envs/licsbas/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 499, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/sar-rnd/anaconda3/envs/licsbas/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 212, in main
    response = requests.get(url)
               ^^^^^^^^^^^^^^^^^
  File "/home/sar-rnd/anaconda3/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sar-rnd/anaconda3/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sar-rnd/anaconda3/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sar-rnd/anaconda3/lib/python3.12/site-packages/requests/sessions.py", line 724, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sar-rnd/anaconda3/lib/python3.12/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2156004788
