### ISSUE TITLE
LiCSBAS process issue

### ISSUE THREAD

**Issue by shubham-rajewar** [yumorishita/LiCSBAS#412]
I have downloaded required data kept in GEOC and GACOS directory, then i started ruuning batch file from second step, it is showing following error. Please suggest me solution for this.
Thank You.

Start step: 02
End step:   16
Log file:   log/202410191641batch_LiCSBAS_02_16.log

"
LiCSBAS02_ml_prep.py ver1.7.4 20201119 Y. Morishita
LiCSBAS02_ml_prep.py -i GEOC -n 1

Create E.geo
  E.geo created

Create N.geo
  N.geo created

Create U.geo
  U.geo created

Create slc.mli
  slc.mli[.png] created

Create hgt
  hgt[.png] created

Create unw and cc

Create EQA.dem_par
Traceback (most recent call last):
  File "/home/gps7/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 453, in <module>
    sys.exit(main())
  File "/home/gps7/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 340, in main
    "width: {}".format(width),
UnboundLocalError: local variable 'width' referenced before assignment "

**Comment by yumorishita** [comment]
The previous run was probably incomplete. I suggest removing GEOCml1 and retry.

**Comment by shubham-rajewar** [comment]
Thank you so much for your response.
As you suggested I removed GEOCml1 dir and tried, Still showing problem
""
Create unw and cc
Create slc.mli.par
Traceback (most recent call last):
  File "/home/gps7/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 453, in <module>
    sys.exit(main())
  File "/home/gps7/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 325, in main
    print('range_samples:   {}'.format(width), file=f)
UnboundLocalError: local variable 'width' referenced before assignment
""

**Comment by yumorishita** [comment]
Then, files in GEOC will probably be corrupted. Please restart from step01.

**Comment by shubham-rajewar** [comment]
Ok, I will check
Thank you!

**Comment by shubham-rajewar** [comment]
Hello sir, I checked with re-downloading data. But still, it shows same error. Earlier, I used to download data directly from websites using wget. As you suggested, I tried to download using step 01, but it is showing some error about exceeding too many redirects for my files. please see the following output: at the end, you will find the error. I think all the installation process is correct. I checked with "LiCSBAS_check_install.py".
Thank you!

"""
Start step: 01
End step:   16
Log file:   log/202410210951batch_LiCSBAS_01_16.log


LiCSBAS01_get_geotiff.py ver1.6.3 20201207 Y. Morishita
LiCSBAS01_get_geotiff.py -f 027A_05791_131313 -s 20180101 -e 20180331 --get_gacos

Frame ID is 027A_05791_131313

Download 027A_05791_131313.geo.E.tif
    027A_05791_131313.geo.E.tif, 24.76MB, 14s, 1.77MB/s
Download 027A_05791_131313.geo.N.tif
    027A_05791_131313.geo.N.tif, 24.76MB, 3s, 8.25MB/s
Download 027A_05791_131313.geo.U.tif
    027A_05791_131313.geo.U.tif, 24.76MB, 11s, 2.25MB/s
Download 027A_05791_131313.geo.hgt.tif
    027A_05791_131313.geo.hgt.tif, 25.53MB, 19s, 1.34MB/s

Download baselines
    baselines, 6.92KB, 1s, 6.92KB/s
Download network.png
    network.png, 1.01MB, 3s, 343.05KB/s
Download metadata.txt
    metadata.txt, 248.0B, 3s, 82.0B/s

Searching latest epoch for mli...
Traceback (most recent call last):
  File "/home/gps7/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 499, in <module>
    sys.exit(main())
  File "/home/gps7/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 212, in main
    response = requests.get(url)
  File "/home/gps7/anaconda3/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/gps7/anaconda3/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/gps7/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/gps7/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/home/gps7/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/home/gps7/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
"""

**Comment by shubham-rajewar** [comment]
Dear Sir, 
Thank you so much for your quick response.
Earlier I was using LiCSBAS instead of LiCSBAS2. Now everything is working properly.
