### ISSUE TITLE
Error of LiCSBAS01_get_geotiff.py？

### ISSUE THREAD

**Issue by sakuya-izayoi-0518** [yumorishita/LiCSBAS#419]
Dir Morishita.
I have a question.

After downloading the sample file: `https://raw.githubusercontent.com/wiki/yumorishita/LiCSBAS/sample/124D_04854_17_1313sample.tar.gz` and deleting all folders except for `batch_LiCSBAS.sh`, I set the following parameters:
```
start_step="01" # 01-05, 11-16
end_step="16"   # 01-05, 11-16
```
However, I encountered the following error:

```
Searching latest epoch for mli...
Traceback (most recent call last):
  File "/root/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 499, in <module>
    sys.exit(main())
  File "/root/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 212, in main
    response = requests.get(url)
  File "/opt/miniconda/envs/licsbas/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/miniconda/envs/licsbas/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/miniconda/envs/licsbas/lib/python3.7/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/miniconda/envs/licsbas/lib/python3.7/site-packages/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "/opt/miniconda/envs/licsbas/lib/python3.7/site-packages/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/miniconda/envs/licsbas/lib/python3.7/site-packages/requests/sessions.py", line 192, in resolve_redirects
    f"Exceeded {self.max_redirects} redirects.", response=resp
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

As far as I can tell, this error occurs because there are too many redirects, preventing access to the final URL.
Could you advise on any possible solutions?

すみません。英語があまりうまくないので、日本語でも補足を記載いたします。

森下様
お世話になっております。
LiCSBASのプログラムを実施しようとしたところ、どうもLiCSBAS01_get_geotiff.pyでリダイレクトが多すぎるというエラーが発生しておるようです。サンプルファイルで、
```
start_step="01" # 01-05, 11-16
end_step="16"   # 01-05, 11-16
```
とした場合も同様でした。何か対処方法はありますでしょうか？

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2156004788

**Comment by sakuya-izayoi-0518** [comment]
Thank you.
