### ISSUE TITLE
LiCSBAS02_ml_prep.py error

### ISSUE THREAD

**Issue by zahraforoodi** [yumorishita/LiCSBAS#422]
dear users
when I use LiCSBAS02_ml_prep.py -i GEOC -n 1, I encounter with the error
Create slc.mli.par
Traceback (most recent call last):
  File "/home/zahra/anaconda3/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 453, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/zahra/anaconda3/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 325, in main
    print('range_samples:   {}'.format(width), file=f)
                                       ^^^^^
UnboundLocalError: cannot access local variable 'width' where it is not associated with a value

**Comment by ferdiansyagz** [comment]
hi zahraforoodi, has your problem been resolved, because i also experienced the same thing, and until now i still can't fix yet

**Comment by zahraforoodi** [comment]
Hi 
dear yumorishita
I upload the log file for you

[202502041300batch_LiCSBAS_01_16.log](https://github.com/user-attachments/files/18655567/202502041300batch_LiCSBAS_01_16.log)

I installed the software in miniconda and anaconda, but I received the same error.
  (miniconda3-latest/envs/licsbas) (base) zahra@zahra:~/LiCSBAS/LiCSBAS$ LiCSBAS_check_install.py


Also, I received the massage 

(miniconda3-latest/envs/licsbas) (base) zahra@zahra:~/LiCSBAS/LiCSBAS$ LiCSBAS_check_install.py

Python version: 3.12.4
  OK

Check required modues and versions
  astropy(6.1.0) OK
  bs4(4.12.3) OK
  h5py(3.11.0) OK
  matplotlib(3.8.4) OK
  numpy(1.26.4) OK
  psutil(5.9.0) OK
  requests(2.32.3) OK
  statsmodels(0.14.2) OK
  gdal(3.6.2) OK

Check LiCSBAS commands
  OK

Check LiCSBAS library
  OK

LiCSBAS install is OK

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2156004788
