### ISSUE TITLE
UnboundLocalError: cannot access local variable 'width' where it is not associated with a value

### ISSUE THREAD

**Issue by ferdiansyagz** [yumorishita/LiCSBAS#424]
![image](https://github.com/user-attachments/assets/8f453974-c069-448a-90a1-86ccfce11418)
How to fix this

**Comment by yumorishita** [comment]
Please upload the full log from step01.

**Comment by ferdiansyagz** [comment]
![image](https://github.com/user-attachments/assets/609cbc48-91cb-437b-93fb-ab72022e5208)
![image](https://github.com/user-attachments/assets/e20200b4-2169-48d5-b762-9dffc2ae6add)
![image](https://github.com/user-attachments/assets/6a2c6c35-f4f4-4825-a563-9efc85b805de)
![image](https://github.com/user-attachments/assets/e25a3c53-abaf-4ea6-8168-81ddbfb93e91)
![image](https://github.com/user-attachments/assets/657f038c-af3e-4bd0-b46e-57ccc82f8381)
![image](https://github.com/user-attachments/assets/5e554c2f-cadd-40af-b3f2-e785ffe4ff6f)
![image](https://github.com/user-attachments/assets/31caf486-2b6a-4296-8024-33c13e2b1635)

**Comment by ferdiansyagz** [comment]
Welcome to Ubuntu 22.04.5 LTS (GNU/Linux 5.15.153.1-microsoft-standard-WSL2 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/pro

 System information as of Thu Nov 28 23:21:54 WIB 2024

  System load:  0.08                Processes:             61
  Usage of /:   0.8% of 1006.85GB   Users logged in:       0
  Memory usage: 11%                 IPv4 address for eth0: 172.27.138.84
  Swap usage:   0%

 * Strictly confined Kubernetes makes edge and IoT secure. Learn how MicroK8s
   just raised the bar for easy, resilient and secure K8s cluster deployment.

   https://ubuntu.com/engage/secure-kubernetes-at-the-edge

This message is shown once a day. To disable it please create the
/home/ferdianzaki/.hushlogin file.
-bash: /home/username/anaconda3/bin/conda: No such file or directory
conda: command not found
(base) ferdianzaki@LAPTOP-DGA0HAOK:~$ git clone https://github.com/yumorishita/LiCSBAS2.git
fatal: destination path 'LiCSBAS2' already exists and is not an empty directory.
(base) ferdianzaki@LAPTOP-DGA0HAOK:~$ rm -rf LiCSBAS2
(base) ferdianzaki@LAPTOP-DGA0HAOK:~$ git clone https://github.com/yumorishita/LiCSBAS2.git
Cloning into 'LiCSBAS2'...
remote: Enumerating objects: 1414, done.
remote: Counting objects: 100% (1414/1414), done.
remote: Compressing objects: 100% (485/485), done.
remote: Total 1414 (delta 842), reused 1361 (delta 805), pack-reused 0 (from 0)
Receiving objects: 100% (1414/1414), 5.71 MiB | 2.84 MiB/s, done.
Resolving deltas: 100% (842/842), done.
(base) ferdianzaki@LAPTOP-DGA0HAOK:~$ cd LiCSBAS/
(base) ferdianzaki@LAPTOP-DGA0HAOK:~/LiCSBAS$ ls
LICENSE  LiCSBAS.yml  LiCSBAS_lib  LiCSBAS_requirements.txt  README.md  bashrc_LiCSBAS.sh  batch_LiCSBAS.sh  bin
(base) ferdianzaki@LAPTOP-DGA0HAOK:~/LiCSBAS$ conda env create -f LiCSBAS.yml
Retrieving notices: ...working... done

CondaValueError: prefix already exists: /home/ferdianzaki/miniconda3/envs/licsbas

(base) ferdianzaki@LAPTOP-DGA0HAOK:~/LiCSBAS$ conda env remove -n licsbas

Remove all packages in environment /home/ferdianzaki/miniconda3/envs/licsbas:

Everything found within the environment (/home/ferdianzaki/miniconda3/envs/licsbas), including any conda environment configurations and any non-conda files, will be deleted. Do you wish to continue?
 (y/[n])? y

(base) ferdianzaki@LAPTOP-DGA0HAOK:~/LiCSBAS$ conda env create -f LiCSBAS.yml
Channels:
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate licsbas
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) ferdianzaki@LAPTOP-DGA0HAOK:~/LiCSBAS$ conda activate licsbas
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:~/LiCSBAS$ source bashrc_licsbas.sh
-bash: bashrc_licsbas.sh: No such file or directory
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:~/LiCSBAS$ source bashcr_LiCSBAS.sh
-bash: bashcr_LiCSBAS.sh: No such file or directory
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:~/LiCSBAS$ source bashrc_LiCSBAS.sh
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:~/LiCSBAS$ LiCSBAS_check_install.py

Python version: 3.12.7
  OK

Check required modues and versions
  astropy(6.1.3) OK
  bs4(4.12.3) OK
  h5py(3.12.1) OK
  matplotlib(3.9.2) OK
  numpy(1.26.4) OK
  psutil(5.9.0) OK
  requests(2.32.3) OK
  statsmodels(0.14.2) OK
  gdal(3.6.2) OK

Check LiCSBAS commands
  OK

Check LiCSBAS library
  OK

LiCSBAS install is OK

(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:~/LiCSBAS$ cd ~
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:~$ ls
LiCSBAS  LiCSBAS2  Miniconda3-latest-Linux-x86_64.sh  Miniconda3-py39_24.7.1-0-Linux-x86_64.sh  miniconda3
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
none            1.9G     0  1.9G   0% /usr/lib/modules/5.15.153.1-microsoft-standard-WSL2
none            1.9G  4.0K  1.9G   1% /mnt/wsl
drivers         476G  460G   16G  97% /usr/lib/wsl/drivers
/dev/sdc       1007G  8.4G  948G   1% /
none            1.9G   84K  1.9G   1% /mnt/wslg
none            1.9G     0  1.9G   0% /usr/lib/wsl/lib
rootfs          1.9G  2.2M  1.9G   1% /init
none            1.9G  488K  1.9G   1% /run
none            1.9G     0  1.9G   0% /run/lock
none            1.9G     0  1.9G   0% /run/shm
tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
none            1.9G   76K  1.9G   1% /mnt/wslg/versions.txt
none            1.9G   76K  1.9G   1% /mnt/wslg/doc
C:\             476G  460G   16G  97% /mnt/c
D:\             448G  208G  240G  47% /mnt/d
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:~$ cd /mnt/d
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d$ ls
ls: cannot access 'DumpStack.log.tmp': Permission denied
ls: cannot access 'pagefile.sys': Permission denied
'$RECYCLE.BIN'       DumpStack.log.tmp   Recovery                         'kuliah extras'
 124D_04854_171313  'KP HIDRONAV'        SteamLibrary                      pagefile.sys
'CV ASW'             KULIAH             'System Volume Information'       'teaser w129 bismillah fix.mp4'
'DATA C'            'Magang BPN'        'TA SKRIPSI'
 DumpStack.log       Prediz             'Windows-SSD (C) - Shortcut.lnk'
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d$ mkdir licsbas
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d$ cd licsbas
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d/licsbas$ ls
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d/licsbas$ mkdir 124D_04854_171313
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d/licsbas$ ls
124D_04854_171313
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d/licsbas$ cd 124D_04854_171313
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d/licsbas/124D_04854_171313$ ls
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d/licsbas/124D_04854_171313$ copy_batch_LiCSBAS.sh

Copy batch_LiCSBAS.sh to the current directory.
(cp -i /home/ferdianzaki/LiCSBAS/batch_LiCSBAS.sh .; chmod 755 batch_LiCSBAS.sh)

Edit batch_LiCSBAS.sh, then run ./batch_LiCSBAS.sh

(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d/licsbas/124D_04854_171313$ ls
batch_LiCSBAS.sh
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d/licsbas/124D_04854_171313$ ./batch_LiCSBAS.sh

Start step: 01
End step:   16
Log file:   log/202411291015batch_LiCSBAS_01_16.log


LiCSBAS01_get_geotiff.py ver1.6.3 20201207 Y. Morishita
LiCSBAS01_get_geotiff.py -s 20160909 -e 20180508

Frame ID is 124D_04854_171313

Download 124D_04854_171313.geo.E.tif
2024-11-29 10:15:52,572 - DEBUG - Starting new HTTP connection (1): gws-access.ceda.ac.uk:80
2024-11-29 10:15:54,089 - DEBUG - http://gws-access.ceda.ac.uk:80 "GET /public/nceo_geohazards/LiCSAR_products/124/124D_04854_171313/metadata/124D_04854_171313.geo.E.tif HTTP/11" 302 138
2024-11-29 10:15:54,090 - DEBUG - Starting new HTTPS connection (1): gws-access.jasmin.ac.uk:443
2024-11-29 10:15:55,805 - DEBUG - https://gws-access.jasmin.ac.uk:443 "GET /public/nceo_geohazards/LiCSAR_products/124/124D_04854_171313/metadata/124D_04854_171313.geo.E.tif HTTP/11" 200 35612970
    124D_04854_171313.geo.E.tif, 33.96MB, 76s, 457.61KB/s
Download 124D_04854_171313.geo.N.tif
2024-11-29 10:17:09,571 - DEBUG - Starting new HTTP connection (1): gws-access.ceda.ac.uk:80
2024-11-29 10:17:11,232 - DEBUG - http://gws-access.ceda.ac.uk:80 "GET /public/nceo_geohazards/LiCSAR_products/124/124D_04854_171313/metadata/124D_04854_171313.geo.N.tif HTTP/11" 302 138
2024-11-29 10:17:11,233 - DEBUG - Starting new HTTPS connection (1): gws-access.jasmin.ac.uk:443
2024-11-29 10:17:12,784 - DEBUG - https://gws-access.jasmin.ac.uk:443 "GET /public/nceo_geohazards/LiCSAR_products/124/124D_04854_171313/metadata/124D_04854_171313.geo.N.tif HTTP/11" 200 35612998
    124D_04854_171313.geo.N.tif, 33.96MB, 71s, 489.83KB/s
Download 124D_04854_171313.geo.U.tif
2024-11-29 10:18:20,791 - DEBUG - Starting new HTTP connection (1): gws-access.ceda.ac.uk:80
2024-11-29 10:18:22,349 - DEBUG - http://gws-access.ceda.ac.uk:80 "GET /public/nceo_geohazards/LiCSAR_products/124/124D_04854_171313/metadata/124D_04854_171313.geo.U.tif HTTP/11" 302 138
2024-11-29 10:18:22,350 - DEBUG - Starting new HTTPS connection (1): gws-access.jasmin.ac.uk:443
2024-11-29 10:18:23,913 - DEBUG - https://gws-access.jasmin.ac.uk:443 "GET /public/nceo_geohazards/LiCSAR_products/124/124D_04854_171313/metadata/124D_04854_171313.geo.U.tif HTTP/11" 200 35612558
    124D_04854_171313.geo.U.tif, 33.96MB, 73s, 476.41KB/s
Download 124D_04854_171313.geo.hgt.tif
2024-11-29 10:19:34,308 - DEBUG - Starting new HTTP connection (1): gws-access.ceda.ac.uk:80
2024-11-29 10:19:35,740 - DEBUG - http://gws-access.ceda.ac.uk:80 "GET /public/nceo_geohazards/LiCSAR_products/124/124D_04854_171313/metadata/124D_04854_171313.geo.hgt.tif HTTP/11" 302 138
2024-11-29 10:19:35,741 - DEBUG - Starting new HTTPS connection (1): gws-access.jasmin.ac.uk:443
2024-11-29 10:19:46,178 - DEBUG - https://gws-access.jasmin.ac.uk:443 "GET /public/nceo_geohazards/LiCSAR_products/124/124D_04854_171313/metadata/124D_04854_171313.geo.hgt.tif HTTP/11" 200 17879631
    124D_04854_171313.geo.hgt.tif, 17.05MB, 43s, 406.06KB/s

Download baselines
2024-11-29 10:20:17,954 - DEBUG - Starting new HTTP connection (1): gws-access.ceda.ac.uk:80
2024-11-29 10:20:19,291 - DEBUG - http://gws-access.ceda.ac.uk:80 "GET /public/nceo_geohazards/LiCSAR_products/124/124D_04854_171313/metadata/baselines HTTP/11" 302 138
2024-11-29 10:20:19,292 - DEBUG - Starting new HTTPS connection (1): gws-access.jasmin.ac.uk:443
2024-11-29 10:20:20,753 - DEBUG - https://gws-access.jasmin.ac.uk:443 "GET /public/nceo_geohazards/LiCSAR_products/124/124D_04854_171313/metadata/baselines HTTP/11" 200 12444
    baselines, 12.15KB, 2s, 6.08KB/s
Download network.png
2024-11-29 10:20:20,903 - DEBUG - Starting new HTTP connection (1): gws-access.ceda.ac.uk:80
2024-11-29 10:20:22,505 - DEBUG - http://gws-access.ceda.ac.uk:80 "GET /public/nceo_geohazards/LiCSAR_products/124/124D_04854_171313/metadata/network.png HTTP/11" 302 138
2024-11-29 10:20:22,506 - DEBUG - Starting new HTTPS connection (1): gws-access.jasmin.ac.uk:443
2024-11-29 10:20:23,762 - DEBUG - https://gws-access.jasmin.ac.uk:443 "GET /public/nceo_geohazards/LiCSAR_products/124/124D_04854_171313/metadata/network.png HTTP/11" 200 844943
    network.png, 825.14KB, 5s, 165.03KB/s
Download metadata.txt
2024-11-29 10:20:26,497 - DEBUG - Starting new HTTP connection (1): gws-access.ceda.ac.uk:80
2024-11-29 10:20:27,990 - DEBUG - http://gws-access.ceda.ac.uk:80 "GET /public/nceo_geohazards/LiCSAR_products/124/124D_04854_171313/metadata/metadata.txt HTTP/11" 302 138
2024-11-29 10:20:27,991 - DEBUG - Starting new HTTPS connection (1): gws-access.jasmin.ac.uk:443
2024-11-29 10:20:29,137 - DEBUG - https://gws-access.jasmin.ac.uk:443 "GET /public/nceo_geohazards/LiCSAR_products/124/124D_04854_171313/metadata/metadata.txt HTTP/11" 200 248
    metadata.txt, 248.0B, 2s, 124.0B/s


LiCSBAS02_ml_prep.py ver1.7.4 20201119 Y. Morishita
LiCSBAS02_ml_prep.py -i GEOC -n 1

Create E.geo
  E.geo created

Create N.geo
  N.geo created

Create U.geo
  U.geo created

Create slc.mli
  No *.geo.mli.tif found in GEOC

Create hgt
  hgt[.png] created

Create unw and cc

Create slc.mli.par
Traceback (most recent call last):
  File "/home/ferdianzaki/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 453, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ferdianzaki/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 325, in main
    print('range_samples:   {}'.format(width), file=f)
                                       ^^^^^
UnboundLocalError: cannot access local variable 'width' where it is not associated with a value
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:~$ cd /mnt/d
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d$ mkdir licsbas2
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d$ cd licsbas2
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d/licsbas2$ ls
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d/licsbas2$ mkdir 054A_09773_111213
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d/licsbas2$ ls
054A_09773_111213
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d/licsbas2$ cd 054A_09773_111213
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d/licsbas2/054A_09773_111213$ ls
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d/licsbas2/054A_09773_111213$ copy_batch_LiCSBAS.sh

Copy batch_LiCSBAS.sh to the current directory.
(cp -i /home/ferdianzaki/LiCSBAS/batch_LiCSBAS.sh .; chmod 755 batch_LiCSBAS.sh)

Edit batch_LiCSBAS.sh, then run ./batch_LiCSBAS.sh

(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d/licsbas2/054A_09773_111213$ ls
batch_LiCSBAS.sh
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d/licsbas2/054A_09773_111213$ ./batch_LiCSBAS.sh

Start step: 01
End step:   16
Log file:   log/202411291031batch_LiCSBAS_01_16.log


LiCSBAS01_get_geotiff.py ver1.6.3 20201207 Y. Morishita
LiCSBAS01_get_geotiff.py

Frame ID is 054A_09773_111213

Download 054A_09773_111213.geo.E.tif
2024-11-29 10:31:33,212 - DEBUG - Starting new HTTP connection (1): gws-access.ceda.ac.uk:80
2024-11-29 10:31:34,789 - DEBUG - http://gws-access.ceda.ac.uk:80 "GET /public/nceo_geohazards/LiCSAR_products/54/054A_09773_111213/metadata/054A_09773_111213.geo.E.tif HTTP/11" 302 138
2024-11-29 10:31:34,791 - DEBUG - Starting new HTTPS connection (1): gws-access.jasmin.ac.uk:443
2024-11-29 10:31:36,372 - DEBUG - https://gws-access.jasmin.ac.uk:443 "GET /public/nceo_geohazards/LiCSAR_products/54/054A_09773_111213/metadata/054A_09773_111213.geo.E.tif HTTP/11" 200 11675736
    054A_09773_111213.geo.E.tif, 11.13MB, 36s, 316.72KB/s
Download 054A_09773_111213.geo.N.tif
2024-11-29 10:32:10,129 - DEBUG - Starting new HTTP connection (1): gws-access.ceda.ac.uk:80
2024-11-29 10:32:11,765 - DEBUG - http://gws-access.ceda.ac.uk:80 "GET /public/nceo_geohazards/LiCSAR_products/54/054A_09773_111213/metadata/054A_09773_111213.geo.N.tif HTTP/11" 302 138
2024-11-29 10:32:11,766 - DEBUG - Starting new HTTPS connection (1): gws-access.jasmin.ac.uk:443
2024-11-29 10:32:13,396 - DEBUG - https://gws-access.jasmin.ac.uk:443 "GET /public/nceo_geohazards/LiCSAR_products/54/054A_09773_111213/metadata/054A_09773_111213.geo.N.tif HTTP/11" 200 11675741
    054A_09773_111213.geo.N.tif, 11.13MB, 21s, 542.96KB/s
Download 054A_09773_111213.geo.U.tif
2024-11-29 10:32:32,063 - DEBUG - Starting new HTTP connection (1): gws-access.ceda.ac.uk:80
2024-11-29 10:32:36,370 - DEBUG - http://gws-access.ceda.ac.uk:80 "GET /public/nceo_geohazards/LiCSAR_products/54/054A_09773_111213/metadata/054A_09773_111213.geo.U.tif HTTP/11" 302 138
2024-11-29 10:32:36,371 - DEBUG - Starting new HTTPS connection (1): gws-access.jasmin.ac.uk:443
2024-11-29 10:32:38,102 - DEBUG - https://gws-access.jasmin.ac.uk:443 "GET /public/nceo_geohazards/LiCSAR_products/54/054A_09773_111213/metadata/054A_09773_111213.geo.U.tif HTTP/11" 200 11675620
    054A_09773_111213.geo.U.tif, 11.13MB, 24s, 475.08KB/s
Download 054A_09773_111213.geo.hgt.tif
2024-11-29 10:32:56,837 - DEBUG - Starting new HTTP connection (1): gws-access.ceda.ac.uk:80
2024-11-29 10:32:58,193 - DEBUG - http://gws-access.ceda.ac.uk:80 "GET /public/nceo_geohazards/LiCSAR_products/54/054A_09773_111213/metadata/054A_09773_111213.geo.hgt.tif HTTP/11" 302 138
2024-11-29 10:32:58,194 - DEBUG - Starting new HTTPS connection (1): gws-access.jasmin.ac.uk:443
2024-11-29 10:33:02,103 - DEBUG - https://gws-access.jasmin.ac.uk:443 "GET /public/nceo_geohazards/LiCSAR_products/54/054A_09773_111213/metadata/054A_09773_111213.geo.hgt.tif HTTP/11" 200 11675604
    054A_09773_111213.geo.hgt.tif, 11.13MB, 33s, 345.51KB/s

Download baselines
2024-11-29 10:33:30,145 - DEBUG - Starting new HTTP connection (1): gws-access.ceda.ac.uk:80
2024-11-29 10:33:31,781 - DEBUG - http://gws-access.ceda.ac.uk:80 "GET /public/nceo_geohazards/LiCSAR_products/54/054A_09773_111213/metadata/baselines HTTP/11" 302 138
2024-11-29 10:33:31,782 - DEBUG - Starting new HTTPS connection (1): gws-access.jasmin.ac.uk:443
2024-11-29 10:33:42,336 - DEBUG - https://gws-access.jasmin.ac.uk:443 "GET /public/nceo_geohazards/LiCSAR_products/54/054A_09773_111213/metadata/baselines HTTP/11" 200 7710
    baselines, 7.53KB, 12s, 642.0B/s
Download network.png
2024-11-29 10:33:42,343 - DEBUG - Starting new HTTP connection (1): gws-access.ceda.ac.uk:80
2024-11-29 10:33:43,817 - DEBUG - http://gws-access.ceda.ac.uk:80 "GET /public/nceo_geohazards/LiCSAR_products/54/054A_09773_111213/metadata/network.png HTTP/11" 302 138
2024-11-29 10:33:43,818 - DEBUG - Starting new HTTPS connection (1): gws-access.jasmin.ac.uk:443
2024-11-29 10:33:45,367 - DEBUG - https://gws-access.jasmin.ac.uk:443 "GET /public/nceo_geohazards/LiCSAR_products/54/054A_09773_111213/metadata/network.png HTTP/11" 200 791415
    network.png, 772.87KB, 5s, 154.57KB/s
Download metadata.txt
2024-11-29 10:33:48,229 - DEBUG - Starting new HTTP connection (1): gws-access.ceda.ac.uk:80
2024-11-29 10:33:48,866 - DEBUG - http://gws-access.ceda.ac.uk:80 "GET /public/nceo_geohazards/LiCSAR_products/54/054A_09773_111213/metadata/metadata.txt HTTP/11" 302 138
2024-11-29 10:33:48,868 - DEBUG - Starting new HTTPS connection (1): gws-access.jasmin.ac.uk:443
2024-11-29 10:33:51,541 - DEBUG - https://gws-access.jasmin.ac.uk:443 "GET /public/nceo_geohazards/LiCSAR_products/54/054A_09773_111213/metadata/metadata.txt HTTP/11" 200 244
    metadata.txt, 244.0B, 3s, 81.0B/s


LiCSBAS02_ml_prep.py ver1.7.4 20201119 Y. Morishita
LiCSBAS02_ml_prep.py -i GEOC -n 1

Create E.geo
  E.geo created

Create N.geo
  N.geo created

Create U.geo
  U.geo created

Create slc.mli
  No *.geo.mli.tif found in GEOC

Create hgt
  hgt[.png] created

Create unw and cc

Create slc.mli.par
Traceback (most recent call last):
  File "/home/ferdianzaki/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 453, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ferdianzaki/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 325, in main
    print('range_samples:   {}'.format(width), file=f)
                                       ^^^^^
UnboundLocalError: cannot access local variable 'width' where it is not associated with a value
(licsbas) ferdianzaki@LAPTOP-DGA0HAOK:/mnt/d/licsbas2/054A_09773_111213$

**Comment by yumorishita** [comment]
You are using an old version which does not work anymore. Please use LiCSBAS2.
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2156004788
