### ISSUE TITLE
Time-sies and plots cannot eb seen, getting error

### ISSUE THREAD

**Issue by SRoy07-bit** [yumorishita/LiCSBAS#430]
Hello,
 I was analysing a frame ID (006D_05509_131313) and then when i ran it, it showed the following and was not able to display the velocity or time-series:
Searching latest epoch for mli...
Traceback (most recent call last):
  File "/home/psaha/Zagros_data/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 499, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/psaha/Zagros_data/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 212, in main
    response = requests.get(url)
               ^^^^^^^^^^^^^^^^^
  File "/home/psaha/anaconda3/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/psaha/anaconda3/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/psaha/anaconda3/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/psaha/anaconda3/lib/python3.12/site-packages/requests/sessions.py", line 724, in send
    history = [resp for resp in gen]
                                ^^^
  File "/home/psaha/anaconda3/lib/python3.12/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
(base) psaha@psaha-ThinkPad-E460:~/Zagros_data/006D_05509_131313$ LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &
[1] 9447
(base) psaha@psaha-ThinkPad-E460:~/Zagros_data/006D_05509_131313$
LiCSBAS_plot_ts.py ver1.13.4 20210910 Y. Morishita
LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5
Traceback (most recent call last):
  File "/home/psaha/Zagros_data/LiCSBAS/bin/LiCSBAS_plot_ts.py", line 256, in <module>
    cmap = tools_lib.get_cmap(cmap_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/psaha/Zagros_data/LiCSBAS/LiCSBAS_lib/LiCSBAS_tools_lib.py", line 431, in get_cmap
    plt.cm.register_cmap(name = cmap_name, cmap = _cmap)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module '[matplotlib.cm](http://matplotlib.cm/)' has no attribute 'register_cmap'

[1]+  Exit 1                  LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5

Can you please help with this error and tell me why teh plots are not being displayed?

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2156004788
