### ISSUE TITLE
Error with time-series plot

### ISSUE THREAD

**Issue by SRoy07-bit** [yumorishita/LiCSBAS#432]
I got the following error when I wanted to view the time-series. Can you help?
LiCSBAS_plot_ts.py -i TS_GEOCml1/cum_filt.h5

LiCSBAS_plot_ts.py ver1.14.0 20230219 Y. Morishita
LiCSBAS_plot_ts.py -i TS_GEOCml1/cum_filt.h5

Reading TS_GEOCml1/cum_filt.h5
Reading TS_GEOCml1/cum.h5 as 2nd
Reading mask
Reading mask
Reading coh_avg
Reading n_unw
Reading vstd
Reading maxTlen
Reading n_gap
Reading stc
Reading n_ifg_noloop
Reading n_loop_err
Reading resid_rms
Reading slc.mli
Reading hgt
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "/home/psaha/Zagros_data/LiCSBAS2/bin/LiCSBAS_plot_ts.py", line 843, in <module>
    printcoords(lastevent)
  File "/home/psaha/Zagros_data/LiCSBAS2/bin/LiCSBAS_plot_ts.py", line 734, in printcoords
    pax2.set_data(jj, ii)
  File "/home/psaha/anaconda3/envs/licsbas/lib/python3.12/site-packages/matplotlib/lines.py", line 665, in set_data
    self.set_xdata(x)
  File "/home/psaha/anaconda3/envs/licsbas/lib/python3.12/site-packages/matplotlib/lines.py", line 1289, in set_xdata
    raise RuntimeError('x must be a sequence')
RuntimeError: x must be a sequence

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS2/issues/78#issue-2505372263

**Comment by SRoy07-bit** [comment]
Hi, I see the comment says downgrade matplotlib version, but I’m already using licsbas2. In that case how do I downgrade the matplotlib version on my python 3.12?

**Comment by yumorishita** [comment]
For example, `conda install matplotlib==3.6.2`
