### ISSUE TITLE
error when using v1.3.20 LiCSBAS01

### ISSUE THREAD

**Issue by sizzer13-13** [yumorishita/LiCSBAS#45]
Hi,
I met a problem when using LiCSBAS01 in the new version of v1.3.20 code. I don't know the reasons:
Checking existing unw and cc (16 parallel, may take time)...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/anaconda3/envs/licsbas/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "anaconda3/envs/licsbas/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Program/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 439, in check_exist_wrapper
    rc = tools_lib.comp_size_time(url_data, path_data)
  File "/Program/LiCSBAS/LiCSBAS_lib/LiCSBAS_tools_lib.py", line 69, in comp_size_time
    size_remote = int(response.headers.get("Content-Length"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 483, in <module>
    sys.exit(main())
  File "/LiCSBAS/bin/LiCSBAS01_get_geotiff.py", line 336, in main
    rc = p.map(check_exist_wrapper, args)
  File "/anaconda3/envs/licsbas/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/anaconda3/envs/licsbas/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by sizzer13-13** [comment]
Mine is Mac OS system.

**Comment by sizzer13-13** [comment]
Sorry. the version # is 1.3.21, not v1.3.20

**Comment by yumorishita** [comment]
Please try restarting your python environment or rebooting your machine.

**Comment by sizzer13-13** [comment]
Even I restart and reboot my machine, it still appears the same problem.

**Comment by yumorishita** [comment]
Could you upload the full log file including lines before the error?

I did not update LiCSBAS01_get_geotiff.py between v1.3.19 and 1.3.21. In what version did you successfully run?

**Comment by yumorishita** [comment]
I wonder if the frame has no ifgs. What is the frame ID?

**Comment by sizzer13-13** [comment]
I run it sucessfully by the older version

**Comment by yumorishita** [comment]
Even in v1.3.19?
Please upload the full log file.

**Comment by yumorishita** [comment]
Has the problem been solved?

**Comment by yumorishita** [comment]
It seems that the problem has been solved. I close this issue.
