### ISSUE TITLE
error in batch processing

### ISSUE THREAD

**Issue by stallinbhandari** [yumorishita/LiCSBAS#73]
hi yumorishita, the following error occurs while running the batchscript

Traceback (most recent call last):
  File "/home/stu/LiCSBAS/bin/LiCSBAS03op_GACOS.py", line 550, in <module>
    sys.exit(main())
  File "/home/stu/LiCSBAS/bin/LiCSBAS03op_GACOS.py", line 369, in main
    plot_lib.plot_gacos_info(gacinfofile, pngfile)
  File "/home/stu/LiCSBAS/LiCSBAS_lib/LiCSBAS_plot_lib.py", line 149, in plot_gacos_info
    ax1.set_xlim(0, xylim1)
  File "/home/stu/miniconda3/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 3297, in set_xlim
    right = self._validate_converted_limits(right, self.convert_xunits)
  File "/home/stu/miniconda3/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 3213, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf

**Comment by stallinbhandari** [comment]
i saw in GACOS_info.txt that some values are nan and inf. What can i do about it?

**Comment by yumorishita** [comment]
I cannot identify the error source from this limited information, but I guess it is because the area of the used GACOS data does not cover the unwrapped data and the corrected unwrapped images are completely nan.

**Comment by yumorishita** [comment]
This problem seems to have been solved. Let me close this issue.
