### ISSUE TITLE
GACOS data unavailable

### ISSUE THREAD

**Issue by nicgar20** [yumorishita/LiCSBAS#87]
Good afternoon.

So I am creating a time series and I want to use the GACOS correction. My problem is that for some reason it is not able to download anything using the `batch_LiCSBAS.sh` file:

This happens:
```
Download GACOS data
  There are 94 epochs from 20141001 to 20210308
  Searching available epochs (4 parallel)...
    0/ 94
   20/ 94
   10/ 94
   30/ 94
   40/ 94
   60/ 94
   50/ 94
   70/ 94
   90/ 94
   80/ 94
  94 GACOS data unavailable
No GACOS data available from 20141001 to 20210308
```

and that or course leads to

```
Traceback (most recent call last):
  File "/home/nicolas/licsbas/LiCSBAS/bin/LiCSBAS03op_GACOS.py", line 550, in <module>
    sys.exit(main())
  File "/home/nicolas/licsbas/LiCSBAS/bin/LiCSBAS03op_GACOS.py", line 369, in main
    plot_lib.plot_gacos_info(gacinfofile, pngfile)
  File "/home/nicolas/licsbas/LiCSBAS/LiCSBAS_lib/LiCSBAS_plot_lib.py", line 147, in plot_gacos_info
    xylim1 = np.max(np.concatenate((std_bf, std_af)))+1
  File "<__array_function__ internals>", line 5, in amax
  File "/home/nicolas/.conda/envs/licsbas/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/home/nicolas/.conda/envs/licsbas/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

BTW: I can download them manually.

How can I get the program to successfully download the GACOS data?

Thank you very much.

**Comment by yumorishita** [comment]
Currently, in most of the frames, the GACOS data are not provided from the LiCS web portal. You need to request the GACOS data from the [GACOS web](http://www.gacos.net/) and download them manually.

**Comment by nicgar20** [comment]
Thank you, I will do it manually then.
